/**
 * Embedded agent hook script source.
 *
 * `vp integration install claude-code` writes this exact TypeScript to
 * `~/.claude/hooks/vision-proxy_read.ts`, and `vp integration install codex`
 * writes it to `~/.codex/hooks/vision-proxy_read.ts`. Each host registers its
 * copy as a plain command (`npx tsx <path>`) in its hooks config, so the
 * config carries only standard keys (type, command, timeout, matcher) and
 * no vision-proxy metadata. The installed file carries a version marker
 * comment so `vp integration status` can report staleness.
 *
 * The script handles both hook events: UserPromptSubmit emits a static Read reminder for prompt image
 * paths plus pasted/attached image refs resolved via the image cache (never
 * shells out, so prompt submission is never blocked), and PreToolUse Read or
 * view_image (image path reads) shells out to `vp analyze` and emits
 * hookSpecificOutput.additionalContext with a deny decision. Fail-open: on any
 * error it exits 0 with no stdout so the agent proceeds unchanged.
 *
 * Composition: the shared analysis policy (path classification, env parsing,
 * reminder rendering, vp resolution) is inlined from the canonical runtime
 * (`src/integrations/runtime.ts`) at generate() time; the adapter below owns only
 * stdio event translation, image-cache refs, the sync executor, and the
 * deny/output shapes. The emitted file stays standalone (no package import).
 *
 * NOTE: this module exports the script source as a raw string. It uses
 * String.raw so regexes inside the generated source are written exactly once.
 * The generated source must therefore never contain a backtick or a dollar
 * sign followed by an opening brace.
 */
import { HOOK_RUNTIME_SOURCE } from "./runtime.ts";

// biome-ignore lint/complexity/noUselessStringRaw: String.raw keeps every composed chunk under the same embedding discipline so a future escape cannot silently interpolate.
const HOOK_SCRIPT_HEADER = String.raw`#!/usr/bin/env -S npx tsx
/**
 * vision-proxy agent hook script.
 *
 * Auto-generated by vp integration install. Do not edit by hand; re-run
 * the installer to regenerate after a vision-proxy upgrade.
 *
 * Prerequisite: tsx must be installed for the host npx tsx command to
 * run this file (e.g. npm install -g tsx).
 *
 * Handles UserPromptSubmit and PreToolUse events: UserPromptSubmit emits
 * a static Read reminder for prompt image paths and pasted or attached
 * image refs resolved via the image cache (never shells out, so prompt
 * submission is never blocked), while PreToolUse analyzes Read-tool or
 * view_image image paths by shelling out to vp analyze, then emits
 * hookSpecificOutput.additionalContext with a deny decision for the agent.
 *
 * Fail-open: on any error it exits 0 with no stdout, so the agent proceeds
 * unchanged. Image-derived text is attacker-controlled, so the analyzer
 * fence stays on.
 */

// __VP_VERSION__PLACEHOLDER__

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

`;

const HOOK_SCRIPT_ADAPTER = String.raw`
var IMAGE_REF_RE = /\[Image #(\d+)\]/g;

function claudeConfigHome(): string {
  var override = process.env.VP_CLAUDE_CONFIG_DIR || process.env.CLAUDE_CONFIG_DIR;
  if (override && override.trim()) return resolve(override.trim());
  var home = process.env.HOME || homedir();
  return join(home, ".claude");
}

function imageCacheDir(): string {
  return join(claudeConfigHome(), "image-cache");
}

function resolveImageRefs(prompt: string, sessionId: string | undefined): string[] {
  var paths: string[] = [];
  var seen: string[] = [];
  if (!sessionId) return paths;
  if (sessionId.indexOf("/") !== -1 || sessionId.indexOf("\\") !== -1 || sessionId.indexOf("..") !== -1 || sessionId === "." || sessionId.trim() === "") return paths;
  var sessionDir = join(imageCacheDir(), sessionId);
  if (!existsSync(sessionDir)) return paths;
  IMAGE_REF_RE.lastIndex = 0;
  var m: RegExpExecArray | null;
  while ((m = IMAGE_REF_RE.exec(prompt)) !== null) {
    var id = Number(m[1]);
    if (!isFinite(id)) continue;
    for (var i = 0; i < IMAGE_EXT.length; i++) {
      var candidate = join(sessionDir, String(id) + "." + IMAGE_EXT[i]);
      if (existsSync(candidate)) {
        if (seen.indexOf(candidate) === -1) {
          seen.push(candidate);
          paths.push(candidate);
        }
        break;
      }
    }
  }
  return paths;
}

function readEvent(): Record<string, any> | null {
  var raw: string;
  try {
    raw = readFileSync(0, "utf8");
  } catch (e) {
    process.stderr.write("[vision-proxy] could not read hook event from stdin\n");
    return null;
  }
  try {
    return JSON.parse(raw);
  } catch (e) {
    process.stderr.write("[vision-proxy] hook event on stdin was not valid JSON\n");
    return null;
  }
}

function readToolInput(event: Record<string, any>): Record<string, any> {
  if (event.tool_input != null && typeof event.tool_input === "object") return event.tool_input;
  if (event.toolInput != null && typeof event.toolInput === "object") return event.toolInput;
  return {};
}

function readToolFilePath(event: Record<string, any>): string | null {
  var toolName = event.tool_name != null ? event.tool_name : event.toolName;
  if (toolName !== "Read" && toolName !== "view_image") return null;
  var toolInput = readToolInput(event);
  var file = toolName === "view_image"
    ? (toolInput.path != null ? toolInput.path : toolInput.file_path)
    : (toolInput.file_path != null ? toolInput.file_path : toolInput.path);
  if (!isImagePath(file)) return null;
  var cwd = typeof event.cwd === "string" ? event.cwd : undefined;
  return resolveImagePath(file, cwd);
}

function runAnalyze(images: string[]): string | null {
  if (!images || images.length === 0) return null;
  var timeout = hookTimeoutMs(process.env.VP_HOOK_TIMEOUT_MS);
  var maxTokens = maxOutputTokens(process.env.VP_MAX_OUTPUT_TOKENS);
  var invocation = buildAnalyzeArgs(images, maxTokens);
  var vp = resolveVpBin();
  var result = spawnSync(invocation.command, invocation.args, {
    encoding: "utf8",
    timeout: timeout,
    maxBuffer: MAX_BUFFER_BYTES,
  }) as { error?: NodeJS.ErrnoException; status?: number | null; stdout?: unknown };
  if (result.error) {
    if (result.error.code === "ENOENT") {
      process.stderr.write("[vision-proxy] vp binary not found: " + vp + "\n");
    } else {
      process.stderr.write("[vision-proxy] vp analyze failed or timed out\n");
    }
    return null;
  }
  var out = String(result.stdout == null ? "" : result.stdout).trim();
  if (result.status !== 0 || !out) {
    process.stderr.write("[vision-proxy] vp analyze exited with status " + String(result.status == null ? "?" : result.status) + "\n");
    return null;
  }
  return out;
}

function emit(eventName: string, description: string, permissionDecision?: string): void {
  var hookSpecificOutput: Record<string, unknown> = {
    hookEventName: eventName,
    additionalContext: description,
  };
  if (permissionDecision) {
    hookSpecificOutput.permissionDecision = permissionDecision;
    hookSpecificOutput.permissionDecisionReason = "Image read intercepted by vision-proxy; see additionalContext for the description.";
  }
  process.stdout.write(JSON.stringify({ hookSpecificOutput: hookSpecificOutput }) + "\n");
}

function runHook(event: Record<string, any> | null): void {
  if (!event) return;
  var eventName = event.hook_event_name != null ? event.hook_event_name : event.hookEventName;
  if (eventName === "UserPromptSubmit") {
    var prompt = typeof event.prompt === "string" ? event.prompt : "";
    var images = extractImagePaths(prompt);
    var sessionId = event.session_id != null ? event.session_id : event.sessionId;
    var refImages = resolveImageRefs(prompt, typeof sessionId === "string" ? sessionId : undefined);
    var allImages = images.concat(refImages);
    if (allImages.length === 0) return;
    emit("UserPromptSubmit", readReminder(allImages, undefined, "prompt", "Read"));
    return;
  }
  if (eventName === "PreToolUse") {
    var file = readToolFilePath(event);
    if (!file) return;
    var desc = runAnalyze([file]);
    if (!desc) return;
    var toolName = event.tool_name != null ? event.tool_name : event.toolName;
    emit("PreToolUse", withImageInstruction(desc, undefined, toolName === "view_image" ? "view_image" : "Read"), "deny");
    return;
  }
}

try {
  runHook(readEvent());
} catch (e) {
  process.stderr.write("[vision-proxy] hook failed open: " + String(e) + "\n");
}
`;

export const HOOK_SCRIPT_SOURCE: string =
	HOOK_SCRIPT_HEADER + HOOK_RUNTIME_SOURCE + HOOK_SCRIPT_ADAPTER;
