/**
 * Embedded agent hook script source.
 *
 * `vp integration install claude-code` writes this exact TypeScript to
 * `~/.claude/hooks/vision-proxy_read.ts`, and `vp integration install codex`
 * writes it to `~/.codex/hooks/vision-proxy_read.ts` (stamped at generate()
 * time to name view_image, the official Codex CLI image tool, in its
 * submit-time reminder; the Claude Code copy names Read). Each host registers its
 * copy as a plain command (`npx tsx <path>`) in its hooks config, so the
 * config carries only standard keys (type, command, timeout, matcher) and
 * no vision-proxy metadata. The installed file carries a version marker
 * comment so `vp integration status` can report staleness.
 *
 * The script handles both hook events: UserPromptSubmit emits a static reminder for prompt image
 * paths (naming the host's native image tool: Read for Claude Code, view_image for Codex)
 * plus pasted/attached image refs resolved via the image cache (never
 * shells out, so prompt submission is never blocked), and PreToolUse Read or
 * view_image (image path reads) shells out to `vp analyze` and emits
 * hookSpecificOutput.additionalContext with a deny decision. Fail-open: on any
 * error it exits 0 with no stdout so the agent proceeds unchanged.
 *
 * Composition: the shared analysis policy (path classification, env parsing,
 * reminder rendering, vp resolution) is inlined from the canonical runtime
 * (`src/integrations/runtime.ts`) at generate() time; the adapter below owns only
 * stdio event translation, image-cache refs, the sync executor, and the
 * deny/output shapes. The emitted file stays standalone (no package import).
 *
 * NOTE: this module exports the script source as a raw string. It uses
 * String.raw so regexes inside the generated source are written exactly once.
 * The generated source must therefore never contain a backtick or a dollar
 * sign followed by an opening brace.
 */
import { HOOK_RUNTIME_SOURCE } from "./runtime.ts";

// biome-ignore lint/complexity/noUselessStringRaw: String.raw keeps every composed chunk under the same embedding discipline so a future escape cannot silently interpolate.
const HOOK_SCRIPT_HEADER = String.raw`#!/usr/bin/env -S npx tsx
/**
 * vision-proxy agent hook script.
 *
 * Auto-generated by vp integration install. Do not edit by hand; re-run
 * the installer to regenerate after a vision-proxy upgrade.
 *
 * Prerequisite: tsx must be installed for the host npx tsx command to
 * run this file (e.g. npm install -g tsx).
 *
 * Handles UserPromptSubmit and PreToolUse events: UserPromptSubmit emits
 * a static reminder for prompt image paths and pasted or attached
 * image refs resolved via the image cache (never shells out, so prompt
 * submission is never blocked). The reminder names the host's native image
 * tool (Read for Claude Code, view_image for Codex, stamped at generate()
 * time), while PreToolUse analyzes Read-tool or
 * view_image image paths by shelling out to vp analyze, then emits
 * hookSpecificOutput.additionalContext with a deny decision for the agent.
 *
 * The PreToolUse analysis is grounded in the recent conversation: the host
 * hands the hook a transcript_path on stdin (CC JSONL, Codex rollout) whose
 * last user/assistant turns are read from disk and formatted into
 * vp analyze --context. The read is bounded and fails open, so a missing or
 * unreadable transcript simply means the analyze call runs without context.
 *
 * Fail-open: on any error it exits 0 with no stdout, so the agent proceeds
 * unchanged. Image-derived text is attacker-controlled, so the analyzer
 * fence stays on.
 */

// __VP_VERSION__PLACEHOLDER__

import { Buffer } from "node:buffer";
import { randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";
import { chmodSync, closeSync, existsSync, lstatSync, mkdirSync, openSync, readdirSync, readFileSync, readSync, rmSync, statSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join, resolve } from "node:path";

`;

const HOOK_SCRIPT_ADAPTER = String.raw`
var IMAGE_REF_RE = /\[Image #(\d+)\]/g;

// Tool word named by the UserPromptSubmit reminder. generate() stamps this
// per host (Read for Claude Code, view_image for Codex) so each artifact
// tells the model to use its native image tool. The PreToolUse deny already
// adapts to the intercepted tool, so only the submit reminder needs this.
var SUBMIT_TOOL_WORD = "Read";

function claudeConfigHome(): string {
  var override = process.env.VP_CLAUDE_CONFIG_DIR || process.env.CLAUDE_CONFIG_DIR;
  if (override && override.trim()) return resolve(override.trim());
  var home = process.env.HOME || homedir();
  return join(home, ".claude");
}

function imageCacheDir(): string {
  return join(claudeConfigHome(), "image-cache");
}

function resolveImageRefs(prompt: string, sessionId: string | undefined): string[] {
  var paths: string[] = [];
  var seen: string[] = [];
  if (!sessionId) return paths;
  if (sessionId.indexOf("/") !== -1 || sessionId.indexOf("\\") !== -1 || sessionId.indexOf("..") !== -1 || sessionId === "." || sessionId.trim() === "") return paths;
  var sessionDir = join(imageCacheDir(), sessionId);
  if (!existsSync(sessionDir)) return paths;
  IMAGE_REF_RE.lastIndex = 0;
  var m: RegExpExecArray | null;
  while ((m = IMAGE_REF_RE.exec(prompt)) !== null) {
    var id = Number(m[1]);
    if (!isFinite(id)) continue;
    for (var i = 0; i < IMAGE_EXT.length; i++) {
      var candidate = join(sessionDir, String(id) + "." + IMAGE_EXT[i]);
      if (existsSync(candidate)) {
        if (seen.indexOf(candidate) === -1) {
          seen.push(candidate);
          paths.push(candidate);
        }
        break;
      }
    }
  }
  return paths;
}

function readEvent(): Record<string, any> | null {
  var raw: string;
  try {
    raw = readFileSync(0, "utf8");
  } catch (e) {
    process.stderr.write("[vision-proxy] could not read hook event from stdin\n");
    return null;
  }
  try {
    return JSON.parse(raw);
  } catch (e) {
    process.stderr.write("[vision-proxy] hook event on stdin was not valid JSON\n");
    return null;
  }
}

function readToolInput(event: Record<string, any>): Record<string, any> {
  if (event.tool_input != null && typeof event.tool_input === "object") return event.tool_input;
  if (event.toolInput != null && typeof event.toolInput === "object") return event.toolInput;
  return {};
}

function readToolFilePath(event: Record<string, any>): string | null {
  var toolName = event.tool_name != null ? event.tool_name : event.toolName;
  if (toolName !== "Read" && toolName !== "view_image") return null;
  var toolInput = readToolInput(event);
  var file = toolName === "view_image"
    ? (toolInput.path != null ? toolInput.path : toolInput.file_path)
    : (toolInput.file_path != null ? toolInput.file_path : toolInput.path);
  if (!isImagePath(file)) return null;
  var cwd = typeof event.cwd === "string" ? event.cwd : undefined;
  return resolveImagePath(file, cwd);
}

// How many transcript lines to parse when rendering --context. Only the
// trailing lines can reach the formatter's last-N window, so bounding the
// parse cost keeps long transcripts cheap; the formatter still trims to its
// own message limit. 400 lines covers the 16-message window even with many
// interleaved tool-result lines.
var TRANSCRIPT_TAIL_LINES = 400;
// How many bytes of the transcript tail to read. 512 KB comfortably covers
// the 400-line window even for large tool-result lines; the read is capped
// so multi-GB transcripts stay cheap.
var TRANSCRIPT_TAIL_BYTES = 512 * 1024;

// Where hook-written context files live: a dedicated directory under the
// OS temp root so the files never sit beside user data. Each file is
// created exclusively (O_EXCL, mode 0600) with 128-bit random entropy and
// deleted by the CLI after reading; stale files are pruned before each
// write (10-minute TTL) so rejected handoffs cannot accumulate.
var CONTEXT_FILE_PREFIX = "vp-context-";
// Stale-file TTL: handoffs older than this are pruned before each write.
var CONTEXT_FILE_TTL_MS = 10 * 60 * 1000;

function contextFileDir(): string {
  var base = "";
  try {
    var tmp = process.env.TMPDIR || process.env.TMP || process.env.TEMP;
    if (tmp && tmp.trim()) base = tmp.trim();
  } catch {
    base = "";
  }
  if (!base) base = tmpdir();
  if (!base) base = "/tmp";
  return join(base, "vision-proxy-context");
}

/**
 * True when an existing context directory is safe to use: not a symlink,
 * owned by the current user, and (unless lax modes are being repaired)
 * mode 0700 with no group/world access. Fail-closed on any stat failure
 * so callers abort rather than write into an untrusted directory.
 */
function isSafeContextDir(dir: string, allowLaxMode?: boolean): boolean {
  var st = null;
  try {
    st = lstatSync(dir);
  } catch {
    return false;
  }
  if (!st) return false;
  try {
    if (st.isSymbolicLink()) return false;
  } catch {
    return false;
  }
  try {
    if (typeof process.getuid === "function" && st.uid !== process.getuid()) return false;
  } catch {
    return false;
  }
  // Lax group/world bits are tolerated only on the pre-repair pass: an
  // existing 0755 directory owned by us is repaired to 0700 below, then
  // rechecked strictly. Ownership and symlink checks always apply.
  if (!allowLaxMode) {
    try {
      if ((st.mode & 0o077) !== 0) return false;
    } catch {
      return false;
    }
  }
  return true;
}

/**
 * Ensure the context directory exists as a private directory: create with
 * mode 0700 when missing, then always validate (fresh or reused) before
 * use. A recursive mkdir that succeeds on an existing directory must not
 * bypass the ownership/permission checks, so validation runs on both
 * paths; lax modes are repaired with chmod 0700 and rechecked. Returns
 * false on any failure (fail open: the caller skips the handoff).
 */
function ensurePrivateContextDir(dir: string): boolean {
  try {
    try {
      mkdirSync(dir, { recursive: true, mode: 0o700 });
    } catch {
      // Exists already or raced creation: fall through to validation.
    }
    // Never trust a fresh-or-reused directory without validating: a
    // pre-created directory may carry permissive modes, wrong ownership,
    // or be a symlink, and recursive mkdir succeeds on it silently.
    // Ownership/symlink are checked first so only our own lax directory
    // reaches the chmod repair; the strict recheck then enforces 0700.
    if (!isSafeContextDir(dir, true)) return false;
    try {
      chmodSync(dir, 0o700);
    } catch {
      // Non-fatal: the strict recheck below still enforces the mode.
    }
    // Recheck after the repair attempt so a failed chmod cannot leave a
    // lax directory in use.
    return isSafeContextDir(dir);
  } catch {
    return false;
  }
}

/**
 * Best-effort prune of stale vp-context-*.txt files older than the TTL.
 * Fail-open: every failure is swallowed so pruning never blocks the
 * handoff. Runs before each write so rejected or interrupted handoffs
 * cannot accumulate forever.
 */
function pruneStaleContextFiles(dir: string): void {
  var entries = null;
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  if (!entries) return;
  var now = Date.now();
  for (var i = 0; i < entries.length; i++) {
    var name = entries[i] || "";
    if (name.indexOf(CONTEXT_FILE_PREFIX) !== 0) continue;
    if (name.slice(-4) !== ".txt") continue;
    var full = join(dir, name);
    var age = -1;
    try {
      age = now - statSync(full).mtimeMs;
    } catch {
      continue;
    }
    if (age < 0 || age <= CONTEXT_FILE_TTL_MS) continue;
    try {
      rmSync(full, { force: true });
    } catch {
      // ignore: best-effort cleanup
    }
  }
}

/**
 * Persist context text to an exclusively-created 0600 tempfile for
 * context-file handoff. Returns the path, or null on any failure (fail
 * open: the caller runs the original command unchanged).
 */
function writeContextFile(context: string): string | null {
  if (!context) return null;
  if (Buffer.byteLength(context, "utf8") > CONTEXT_FILE_MAX_BYTES) return null;
  var dir = contextFileDir();
  try {
    if (!ensurePrivateContextDir(dir)) return null;
    pruneStaleContextFiles(dir);
    var fd = -1;
    var file = "";
    var attempts = 0;
    while (fd === -1 && attempts < 5) {
      attempts++;
      // 128-bit random entropy: unlinkable without directory listing,
      // unlike the prior timestamp+pid sequence.
      var name = CONTEXT_FILE_PREFIX + randomBytes(16).toString("hex") + ".txt";
      file = join(dir, name);
      try {
        // O_EXCL: fail when the path already exists instead of following
        // a pre-created symlink or overwriting another process's file.
        fd = openSync(file, "wx", 0o600);
      } catch {
        fd = -1;
        file = "";
      }
    }
    if (fd === -1 || !file) return null;
    try {
      writeFileSync(fd, context, { encoding: "utf8" });
    } catch {
      // A failed write may leave a partial file at its final path with no
      // later prune guaranteed. Close first: unlinking an open descriptor
      // fails on platforms such as Windows, and the finally below would
      // then only close without retrying the removal.
      try {
        closeSync(fd);
      } catch {
        // ignore: descriptor cleanup is best-effort
      }
      fd = -1;
      try {
        rmSync(file, { force: true });
      } catch {
        // ignore: best-effort failure cleanup
      }
      return null;
    } finally {
      // fd is -1 when the catch above already closed it.
      if (fd !== -1) {
        try {
          closeSync(fd);
        } catch {
          // ignore: descriptor cleanup is best-effort
        }
      }
    }
    try {
      chmodSync(file, 0o600);
    } catch {
      // ignore: creation mode already requested 0600
    }
    return file;
  } catch {
    return null;
  }
}

function runAnalyze(images: string[], extras): string | null {
  if (!images || images.length === 0) return null;
  var timeout = hookTimeoutMs(process.env.VP_HOOK_TIMEOUT_MS);
  var maxTokens = maxOutputTokens(process.env.VP_MAX_OUTPUT_TOKENS);
  var invocation = buildAnalyzeArgs(images, maxTokens, extras);
  var vp = resolveVpBin();
  // Sensitive question/context travel on stdin, never argv, so a local
  // process listing cannot capture conversation content (CWE-214). Omit
  // the input entirely when there is nothing sensitive to send.
  var opts: Record<string, unknown> = {
    encoding: "utf8",
    timeout: timeout,
    maxBuffer: MAX_BUFFER_BYTES,
  };
  if (invocation.stdin) opts.input = invocation.stdin;
  var result = spawnSync(invocation.command, invocation.args, opts) as { error?: NodeJS.ErrnoException; status?: number | null; stdout?: unknown };
  if (result.error) {
    if (result.error.code === "ENOENT") {
      process.stderr.write("[vision-proxy] vp binary not found: " + vp + "\n");
    } else {
      process.stderr.write("[vision-proxy] vp analyze failed or timed out\n");
    }
    return null;
  }
  var out = String(result.stdout == null ? "" : result.stdout).trim();
  if (result.status !== 0 || !out) {
    process.stderr.write("[vision-proxy] vp analyze exited with status " + String(result.status == null ? "?" : result.status) + "\n");
    return null;
  }
  return out;
}

// Read the host's on-disk transcript (CC JSONL or Codex rollout) and render
// its last user/assistant turns into the analyze --context value.
//
// CC lines: { type: "user" | "assistant", message: { role, content } } where
// content is a string or block array. Tool-result user lines carry no text
// blocks, so they contribute nothing.
//
// Codex lines: { type: "response_item", payload: { type: "message", role,
// content: [{ type: "input_text" | "output_text", text }] } }.
//
// Both map to the plain { role, content } shape the formatter expects;
// unrecognized lines are skipped. Only the tail is read so long transcripts
// stay cheap, and any error fails open to "".
function readTranscriptContext(transcriptPath: string | undefined): string {
  if (!transcriptPath || !existsSync(transcriptPath)) return "";
  var size: number;
  try {
    size = statSync(transcriptPath).size;
  } catch {
    return "";
  }
  if (size === 0) return "";
  var start = Math.max(0, size - TRANSCRIPT_TAIL_BYTES);
  var buf = Buffer.alloc(size - start);
  var fd: number;
  try {
    fd = openSync(transcriptPath, "r");
  } catch {
    return "";
  }
  var bytesRead: number;
  try {
    bytesRead = readSync(fd, buf, 0, size - start, start);
  } finally {
    closeSync(fd);
  }
  // readSync may return fewer bytes than requested (POSIX short read, and a
  // live transcript can shrink between statSync and the read); decode only
  // the bytes actually read so the alloc's zero-fill never reaches the parser.
  var raw = buf.subarray(0, bytesRead).toString("utf8");
  // When reading from mid-file, discard the first (partial) line.
  var lines: string[];
  if (start > 0) {
    var firstNewline = raw.indexOf("\n");
    if (firstNewline === -1) return "";
    lines = raw.slice(firstNewline + 1).split("\n");
  } else {
    lines = raw.split("\n");
  }
  var tail = lines.slice(-TRANSCRIPT_TAIL_LINES).map(function (l) { return l.trim(); }).filter(Boolean);
  var msgs: Array<{ role?: unknown; content?: unknown }> = [];
  for (const line of tail) {
    var rec: any;
    try {
      rec = JSON.parse(line);
    } catch {
      continue;
    }
    if (!rec || typeof rec !== "object") continue;
    var role: unknown;
    var content: unknown;
    if (rec.type === "user" || rec.type === "assistant") {
      // CC transcript line.
      var message = rec.message;
      if (!message || typeof message !== "object") continue;
      role = message.role;
      content = message.content;
    } else if (rec.type === "response_item" && rec.payload && rec.payload.type === "message") {
      // Codex rollout line.
      role = rec.payload.role;
      // Normalize Codex input_text/output_text blocks to plain text blocks so
      // the shared formatter counts only text.
      var blocks = Array.isArray(rec.payload.content) ? rec.payload.content : [];
      content = blocks.map(function (b) {
        if (b && (b.type === "input_text" || b.type === "output_text")) {
          return { type: "text", text: b.text };
        }
        return b;
      });
    } else {
      continue;
    }
    if (role === "user" || role === "assistant") msgs.push({ role: role, content: content });
  }
  return buildConversationContext(msgs);
}

function emit(
  eventName: string,
  description: string,
  permissionDecision?: string,
  updatedInput?: Record<string, unknown>,
): void {
  var hookSpecificOutput: Record<string, unknown> = {
    hookEventName: eventName,
    additionalContext: description,
  };
  if (permissionDecision) {
    hookSpecificOutput.permissionDecision = permissionDecision;
    hookSpecificOutput.permissionDecisionReason = "Image read intercepted by vision-proxy; see additionalContext for the description.";
  }
  if (updatedInput) {
    hookSpecificOutput.updatedInput = updatedInput;
  }
  process.stdout.write(JSON.stringify({ hookSpecificOutput: hookSpecificOutput }) + "\n");
}

function runHook(event: Record<string, any> | null): void {
  if (!event) return;
  var eventName = event.hook_event_name != null ? event.hook_event_name : event.hookEventName;
  if (eventName === "UserPromptSubmit") {
    var prompt = typeof event.prompt === "string" ? event.prompt : "";
    var images = extractImagePaths(prompt);
    var sessionId = event.session_id != null ? event.session_id : event.sessionId;
    var refImages = resolveImageRefs(prompt, typeof sessionId === "string" ? sessionId : undefined);
    var allImages = images.concat(refImages);
    if (allImages.length === 0) return;
    emit("UserPromptSubmit", readReminder(allImages, undefined, "prompt", SUBMIT_TOOL_WORD));
    return;
  }
  if (eventName === "PreToolUse") {
    // Shell-tool rewrite path (U3): a model-invoked analyze command gets
    // its recent conversation context via a tempfile reference. The hook
    // writes the context the transcript handed it and appends
    // --context-file to the model's own command, which then executes
    // (allow + updatedInput). Fail open: any failure emits nothing so the
    // original command runs unchanged.
    var toolNameEarly = event.tool_name != null ? event.tool_name : event.toolName;
    if (toolNameEarly === "Bash") {
      var toolInputEarly = readToolInput(event);
      var rawCommand = typeof toolInputEarly.command === "string" ? toolInputEarly.command : "";
      if (rawCommand && isUnflaggedAnalyzeCommand(rawCommand)) {
        var shellContext = "";
        try {
          shellContext = readTranscriptContext(
            event.transcript_path != null ? event.transcript_path : event.transcriptPath,
          );
        } catch {
          shellContext = "";
        }
        if (shellContext) {
          var contextPath = writeContextFile(shellContext);
          if (contextPath) {
            var rewritten = appendContextFileArg(rawCommand, quoteShellArg(contextPath));
            process.stdout.write(
              JSON.stringify({ hookSpecificOutput: {
                hookEventName: "PreToolUse",
                permissionDecision: "allow",
                updatedInput: { command: rewritten },
              } }) + "\n",
            );
            return;
          }
        }
        return;
      }
      return;
    }
    var file = readToolFilePath(event);
    if (!file) return;
    // Ground the description in the recent conversation by reading the host
    // transcript the hook was handed (CC JSONL or Codex rollout). Fail open:
    // an unreadable or unrecognized transcript means analyze runs without
    // context rather than the read being blocked.
    var context = "";
    try {
      context = readTranscriptContext(
        event.transcript_path != null ? event.transcript_path : event.transcriptPath,
      );
    } catch {
      context = "";
    }
    var desc = runAnalyze([file], context ? { context } : undefined);
    if (!desc) return;
    var toolName = event.tool_name != null ? event.tool_name : event.toolName;
    emit("PreToolUse", withImageInstruction(desc, undefined, toolName === "view_image" ? "view_image" : "Read"), "deny");
    return;
  }
}

try {
  runHook(readEvent());
} catch (e) {
  process.stderr.write("[vision-proxy] hook failed open: " + String(e) + "\n");
}
`;

export const HOOK_SCRIPT_SOURCE: string =
	HOOK_SCRIPT_HEADER + HOOK_RUNTIME_SOURCE + HOOK_SCRIPT_ADAPTER;
