/**
 * Embedded opencode v1 plugin source.
 *
 * `vp integration install opencode` writes this exact TypeScript into
 * `~/.config/opencode/plugins/vision-proxy_read.ts`. opencode auto-loads local
 * plugins from that directory, so it must run as plain TypeScript with no
 * build step.
 *
 * The plugin registers hooks for parity with claude-code/codex:
 * - `chat.message`: extracts image paths from the user text and appends a
 *   static reminder to inspect each one with the read tool (like
 *   UserPromptSubmit). It never shells out, so message handling stays fast;
 *   the actual analysis happens lazily in `tool.execute.before` when the
 *   model reads the image. Attached image parts are left untouched so the
 *   model sees them natively.
 * - `tool.execute.before`: the single analysis point. Intercepts `read` tool
 *   calls on image files, runs `vp analyze`, and denies the read by throwing
 *   an error whose message carries the description (like PreToolUse Read).
 *
 * Image reads are unconditional by design (like the claude-code/codex hooks):
 * installing the plugin is the user's explicit opt-in to route every image
 * read through vision-proxy; uninstalling restores native image input. The
 * model's modality is deliberately not inspected.
 *
 * Injected reminder parts carry a stable marker prefix so previously
 * injected context can be stripped if the hook ever re-fires for the same
 * message, keeping the prompt free of duplicated reminders.
 *
 * No new `analyze_image` tool is registered - the agent uses its native Read
 * tool, which the hook intercepts.
 *
 * Fail-open: if `vp` is missing or exits non-zero, the hook logs and leaves
 * the original message or tool call unchanged.
 *
 * Composition: the shared analysis policy (path classification, env parsing,
 * reminder rendering, vp resolution) is inlined from the canonical runtime
 * (`src/integrations/runtime.ts`) at generate() time; the adapter below owns only
 * opencode lifecycle translation, the execFile executor, and the
 * throw-to-deny output shape. The emitted file stays standalone (no package
 * import).
 *
 * NOTE: this module exports the plugin source as a raw string. It uses
 * String.raw so regexes inside the generated source are written exactly once.
 * The generated source must therefore never contain a backtick or a dollar
 * sign followed by an opening brace.
 */
import { HOOK_RUNTIME_SOURCE } from "./runtime.ts";

// biome-ignore lint/complexity/noUselessStringRaw: String.raw keeps every composed chunk under the same embedding discipline so a future escape cannot silently interpolate.
const OPENCODE_PLUGIN_HEADER = String.raw`/**
 * vision-proxy opencode plugin.
 *
 * Auto-generated by vp integration install opencode. Do not edit by hand;
 * re-run the installer to regenerate after a vision-proxy upgrade.
 *
 * Registers hooks for parity with claude-code/codex:
 * - chat.message -> like UserPromptSubmit (appends a static reminder to read
 *   referenced image paths; never shells out so message handling stays fast)
 * - tool.execute.before (read) -> like PreToolUse Read (the single analysis
 *   point: intercepts reads on images, runs vp analyze, denies the read)
 *
 * Image reads are always routed through vision-proxy, for every model:
 * installing this plugin is the opt-in to route all image reads through
 * vision-proxy. Attached image parts are left untouched so the model sees
 * them natively.
 *
 * No new analyze_image tool - the agent uses native Read which hook intercepts.
 *
 * Injected reminder text starts with a stable marker so prior injections
 * are stripped if the hook re-fires, preventing duplicated context.
 *
 * The description text returned by vp is attacker-controlled (it comes from
 * an external vision model), so it is forwarded verbatim inside its UNTRUSTED
 * fence and the consumer must treat it as untrusted input.
 */
import type { Hooks } from "@opencode-ai/plugin";
import { execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

// __VP_VERSION__PLACEHOLDER__

`;

const OPENCODE_PLUGIN_ADAPTER = String.raw`
var TIMEOUT_MS = hookTimeoutMs(process.env.VP_HOOK_TIMEOUT_MS);
// Stable prefix on every injected reminder and deny message. Aliases the
// canonical marker so the hook recognizes and strips its own prior reminders
// if the same message is ever processed again, so context is never duplicated.
var INJECTION_MARKER = REMINDER_MARKER;

/** Run vp analyze and return the fenced description, or null on failure.
 * Only the tool.execute.before (read) path calls this: chat.message emits a
 * static Read reminder instead so message handling never waits on a vision
 * call. Uses an async child process so image analysis never blocks the host
 * event loop. */
async function runAnalyze(images: string[]): Promise<string | null> {
  if (images.length === 0) return null;
  var vp = resolveVpBin();
  var maxTokens = maxOutputTokens(process.env.VP_MAX_OUTPUT_TOKENS);
  var invocation = buildAnalyzeArgs(images, maxTokens);
  var result = await runVp(invocation.command, invocation.args);
  if (result.error) {
    if ((result.error as NodeJS.ErrnoException).code === "ENOENT") {
      console.error("[vision-proxy] vp binary not found: " + vp);
    } else { console.error("[vision-proxy] vp analyze failed or timed out"); }
    return null;
  }
  if (result.status !== 0 || !result.stdout.trim()) {
    console.error("[vision-proxy] vp analyze exited with status " + (result.status ?? "?"));
    return null;
  }
  return result.stdout.trimEnd();
}

/** Promise wrapper around execFile that returns a spawnSync-shaped result
 * ({ status, stdout, stderr, error }) so the rest of the plugin can treat
 * timeouts, ENOENT, and fail-open uniformly. */
function runVp(
  command: string,
  args: string[],
): Promise<{ status: number; stdout: string; stderr: string; error?: NodeJS.ErrnoException }> {
  return new Promise((resolve) => {
    execFile(
      command,
      args,
      { encoding: "utf8", timeout: TIMEOUT_MS, maxBuffer: MAX_BUFFER_BYTES },
      (error, stdout, stderr) => {
        if (error) {
          resolve({ status: 1, stdout: stdout ?? "", stderr: stderr ?? "", error: error as NodeJS.ErrnoException });
        } else {
          resolve({ status: 0, stdout: stdout ?? "", stderr: stderr ?? "", error: undefined });
        }
      },
    );
  });
}

/** Monotonic part id generator; opencode requires ids to start with "prt". */
let partCounter = 0;
function newPartId(): string {
  partCounter += 1;
  return "prt-vp-" + Date.now().toString(36) + "-" + partCounter + "-" + Math.random().toString(36).slice(2, 8);
}

async function handleChatMessage(
  input: { sessionID: string; messageID?: string },
  output: { message: { sessionID?: string }; parts: any[] },
  cwd: string,
): Promise<void> {
  // Idempotency guard: strip reminder parts injected by a previous run of
  // this hook before collecting text, so re-delivery never duplicates context.
  for (let i = output.parts.length - 1; i >= 0; i--) {
    const prior: any = output.parts[i];
    if (prior?.type === "text" && typeof prior.text === "string" && prior.text.startsWith(INJECTION_MARKER)) {
      output.parts.splice(i, 1);
    }
  }
  // Collect the user-visible text and resolve referenced image paths.
  const textChunks: string[] = [];
  for (const part of output.parts as any[]) {
    if (part?.type === "text" && typeof part.text === "string") {
      textChunks.push(part.text);
    }
  }
  const promptText = textChunks.join("\n");
  const images: string[] = [];
  for (const candidate of extractImagePaths(promptText)) {
    const resolvedPath = resolveImagePath(candidate, cwd);
    if (resolvedPath && isImagePath(resolvedPath) && existsSync(resolvedPath)) images.push(resolvedPath);
  }
  const uniqueImages = [...new Set(images)];
  if (uniqueImages.length === 0) return;
  // Reminder only: never shell out to vp analyze here. A slow or stuck
  // vision call used to delay message handling; the actual analysis happens
  // lazily in tool.execute.before when the model reads the image. Attached
  // image parts are left untouched so the model sees them natively.
  const anchor: any = output.parts[output.parts.length - 1];
  output.parts.push({
    id: newPartId(),
    sessionID: anchor?.sessionID ?? output.message?.sessionID ?? input.sessionID,
    messageID: anchor?.messageID ?? output.message?.id ?? input.messageID,
    type: "text",
    synthetic: true,
    text: readReminder(uniqueImages, INJECTION_MARKER, "message", "read"),
  });
}

async function handleToolExecuteBefore(
  input: { tool: string },
  output: { args: any },
  cwd: string,
): Promise<void> {
  if (input.tool !== "read") return;
  const argPath =
    output.args && typeof output.args.path === "string"
      ? output.args.path
      : output.args && typeof output.args.filePath === "string"
        ? output.args.filePath
        : undefined;
  if (!isImagePath(argPath)) return;
  const filePath = resolveImagePath(argPath, cwd);
  if (!filePath || !existsSync(filePath)) return;
  const description = await runAnalyze([filePath]);
  // Fail-open: when analysis is unavailable, allow the original read.
  if (!description) return;
  // Denying by throw surfaces this message to the model as the tool result,
  // which carries both the instruction and the description.
  throw new Error(withImageInstruction(description, INJECTION_MARKER));
}

export default async function visionProxyPlugin(input: {
  directory?: string;
}): Promise<Hooks> {
  const pluginCwd = typeof input?.directory === "string" && input.directory ? input.directory : process.cwd();
  return {
    "chat.message": async (innerInput, innerOutput) => {
      await handleChatMessage(innerInput as any, innerOutput as any, pluginCwd);
    },
    "tool.execute.before": async (innerInput, innerOutput) => {
      await handleToolExecuteBefore(innerInput as any, innerOutput as any, pluginCwd);
    },
  };
}
`;

export const OPENCODE_PLUGIN_SOURCE: string =
	OPENCODE_PLUGIN_HEADER + HOOK_RUNTIME_SOURCE + OPENCODE_PLUGIN_ADAPTER;
