/**
 * Embedded opencode v1 plugin source.
 *
 * `vp integration install opencode` writes this exact TypeScript into
 * `~/.config/opencode/plugins/vision-proxy_read.ts`. opencode auto-loads local
 * plugins from that directory, so it must run as plain TypeScript with no
 * build step.
 *
 * The plugin registers hooks for parity with claude-code/codex:
 * - `chat.message`: extracts image paths from the user text and appends a
 *   static reminder to inspect each one with the read tool (like
 *   UserPromptSubmit). It never shells out, so message handling stays fast;
 *   the actual analysis happens lazily in `tool.execute.before` when the
 *   model reads the image. Attached image parts are left untouched so the
 *   model sees them natively.
 * - `tool.execute.before`: the single analysis point. Intercepts `read` tool
 *   calls on image files, runs `vp analyze`, and denies the read by throwing
 *   an error whose message carries the description (like PreToolUse Read).
 *   The session's last user/assistant messages are fetched through the
 *   plugin's SDK client (`client.session.messages`) and formatted into
 *   `vp analyze --context` so the description is grounded in the recent
 *   conversation; the lookup fails open to no context on any error.
 *
 * Image reads are unconditional by design (like the claude-code/codex hooks):
 * installing the plugin is the user's explicit opt-in to route every image
 * read through vision-proxy; uninstalling restores native image input. The
 * model's modality is deliberately not inspected.
 *
 * Injected reminder parts carry a stable marker prefix so previously
 * injected context can be stripped if the hook ever re-fires for the same
 * message, keeping the prompt free of duplicated reminders.
 *
 * No new `analyze_image` tool is registered - the agent uses its native Read
 * tool, which the hook intercepts.
 *
 * Fail-open: if `vp` is missing or exits non-zero, the hook logs and leaves
 * the original message or tool call unchanged.
 *
 * Composition: the shared analysis policy (path classification, env parsing,
 * reminder rendering, vp resolution) is inlined from the canonical runtime
 * (`src/integrations/runtime.ts`) at generate() time; the adapter below owns only
 * opencode lifecycle translation, the execFile executor, and the
 * throw-to-deny output shape. The emitted file stays standalone (no package
 * import).
 *
 * NOTE: this module exports the plugin source as a raw string. It uses
 * String.raw so regexes inside the generated source are written exactly once.
 * The generated source must therefore never contain a backtick or a dollar
 * sign followed by an opening brace.
 */
import { HOOK_RUNTIME_SOURCE } from "./runtime.ts";

// biome-ignore lint/complexity/noUselessStringRaw: String.raw keeps every composed chunk under the same embedding discipline so a future escape cannot silently interpolate.
const OPENCODE_PLUGIN_HEADER = String.raw`/**
 * vision-proxy opencode plugin.
 *
 * Auto-generated by vp integration install opencode. Do not edit by hand;
 * re-run the installer to regenerate after a vision-proxy upgrade.
 *
 * Registers hooks for parity with claude-code/codex:
 * - chat.message -> like UserPromptSubmit (appends a static reminder to read
 *   referenced image paths; never shells out so message handling stays fast)
 * - tool.execute.before (read) -> like PreToolUse Read (the single analysis
 *   point: intercepts reads on images, runs vp analyze, denies the read)
 *
 * Image reads are always routed through vision-proxy, for every model:
 * installing this plugin is the opt-in to route all image reads through
 * vision-proxy. Attached image parts are left untouched so the model sees
 * them natively.
 *
 * No new analyze_image tool - the agent uses native Read which hook intercepts.
 *
 * Injected reminder text starts with a stable marker so prior injections
 * are stripped if the hook re-fires, preventing duplicated context.
 *
 * The description text returned by vp is attacker-controlled (it comes from
 * an external vision model), so it is forwarded verbatim inside its UNTRUSTED
 * fence and the consumer must treat it as untrusted input.
 */
import type { Hooks } from "@opencode-ai/plugin";
import { randomBytes } from "node:crypto";
import { execFile } from "node:child_process";
import { chmodSync, closeSync, existsSync, lstatSync, mkdirSync, openSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join, resolve } from "node:path";

// __VP_VERSION__PLACEHOLDER__

`;

const OPENCODE_PLUGIN_ADAPTER = String.raw`
var TIMEOUT_MS = hookTimeoutMs(process.env.VP_HOOK_TIMEOUT_MS);
// Stable prefix on every injected reminder and deny message. Aliases the
// canonical marker so the hook recognizes and strips its own prior reminders
// if the same message is ever processed again, so context is never duplicated.
var INJECTION_MARKER = REMINDER_MARKER;

/** Fetch the session's messages through the plugin's SDK client and render
 * the last user/assistant turns as the analyze --context value. Fails open:
 * a missing client, a failed request, or an unrecognized shape yields "". */
async function loadConversationContext(client, sessionID): Promise<string> {
  if (!client || !sessionID || !client.session || !client.session.messages) return "";
  // Bound the request so a wedged server can never hold up the read hook. The
  // race timer is cleared on completion; a losing timer alone keeps the
  // event loop alive for at most 5s, which is harmless in-process.
  var result = await new Promise((resolve) => {
    var settled = false;
    var timer = setTimeout(function () {
      if (!settled) { settled = true; resolve(null); }
    }, 5000);
    Promise.resolve(client.session.messages({ path: { id: sessionID } })).then(
      (r) => {
        if (!settled) { settled = true; clearTimeout(timer); resolve(r); }
      },
      () => {
        if (!settled) { settled = true; clearTimeout(timer); resolve(null); }
      },
    );
  });
  if (!result) return "";
  // The SDK lists messages chronologically (newest last). Map each entry's
  // info/parts to the plain { role, content } shape the formatter expects;
  // parts that are not text blocks are ignored by it. Our own injected
  // reminder parts are stripped first: chat.message appends them as
  // persistent synthetic parts, and without this they would echo back
  // into every later analyze call (~97% boilerplate per user turn) and
  // feed a read-tool instruction to a vision model that has no tools.
  var msgs = (Array.isArray(result.data) ? result.data : [])
    .filter((m) => m && m.info && Array.isArray(m.parts))
    .map((m) => ({
      role: m.info.role,
      content: m.parts.filter(function (p) {
        return !(p && p.type === "text" && typeof p.text === "string" && p.text.indexOf(INJECTION_MARKER) === 0);
      }),
    }));
  return buildConversationContext(msgs);
}

/** Run vp analyze and return the fenced description, or null on failure.
 * Only the tool.execute.before (read) path calls this: chat.message emits a
 * static Read reminder instead so message handling never waits on a vision
 * call. Sensitive question/context travel on stdin, never argv. Uses an async
 * child process so image analysis never blocks the host event loop. */
async function runAnalyze(images: string[], extras): Promise<string | null> {
  if (images.length === 0) return null;
  var vp = resolveVpBin();
  var maxTokens = maxOutputTokens(process.env.VP_MAX_OUTPUT_TOKENS);
  var invocation = buildAnalyzeArgs(images, maxTokens, extras);
  var result = await runVp(invocation.command, invocation.args, invocation.stdin);
  if (result.error) {
    if ((result.error as NodeJS.ErrnoException).code === "ENOENT") {
      console.error("[vision-proxy] vp binary not found: " + vp);
    } else { console.error("[vision-proxy] vp analyze failed or timed out"); }
    return null;
  }
  if (result.status !== 0 || !result.stdout.trim()) {
    console.error("[vision-proxy] vp analyze exited with status " + (result.status ?? "?"));
    return null;
  }
  return result.stdout.trimEnd();
}

/** Promise wrapper around execFile that returns a spawnSync-shaped result
 * ({ status, stdout, stderr, error }) so the rest of the plugin can treat
 * timeouts, ENOENT, and fail-open uniformly. The sensitive payload travels
 * on stdin (CWE-214); stdinText is "" when there is nothing to send. */
function runVp(
  command: string,
  args: string[],
  stdinText: string,
): Promise<{ status: number; stdout: string; stderr: string; error?: NodeJS.ErrnoException }> {
  return new Promise((resolve) => {
    var child;
    try {
      child = execFile(
        command,
        args,
        { encoding: "utf8", timeout: TIMEOUT_MS, maxBuffer: MAX_BUFFER_BYTES },
        (error, stdout, stderr) => {
          if (error) {
            resolve({ status: 1, stdout: stdout ?? "", stderr: stderr ?? "", error: error as NodeJS.ErrnoException });
          } else {
            resolve({ status: 0, stdout: stdout ?? "", stderr: stderr ?? "", error: undefined });
          }
        },
      );
      // A child that exits before stdin drains raises EPIPE on the write;
      // the callback above still settles the promise, so swallow it here.
      var onPipeError = function () { /* callback settles */ };
      child.stdin.on("error", onPipeError);
      if (stdinText) {
        try { child.stdin.write(stdinText); } catch { /* callback settles */ }
      }
      try { child.stdin.end(); } catch { /* callback settles */ }
    } catch (err) {
      resolve({ status: 1, stdout: "", stderr: "", error: err as NodeJS.ErrnoException });
    }
  });
}

var CONTEXT_FILE_PREFIX = "vp-context-";
// Stale-file TTL: handoffs older than this are pruned before each write.
var CONTEXT_FILE_TTL_MS = 10 * 60 * 1000;

function contextFileDir(): string {
  var base = "";
  try {
    var tmp = process.env.TMPDIR || process.env.TMP || process.env.TEMP;
    if (tmp && tmp.trim()) base = tmp.trim();
  } catch {
    base = "";
  }
  if (!base) {
    try {
      base = tmpdir();
    } catch {
      base = "";
    }
  }
  if (!base) base = "/tmp";
  return join(base, "vision-proxy-context");
}

/**
 * True when an existing context directory is safe to reuse: not a symlink,
 * owned by the current user, and mode 0700 (no group/world access).
 * Fail-closed on any stat failure so callers abort rather than write into
 * an untrusted directory.
 */
function isSafeContextDir(dir: string): boolean {
  var st = null;
  try {
    st = lstatSync(dir);
  } catch {
    return false;
  }
  if (!st) return false;
  try {
    if (st.isSymbolicLink()) return false;
  } catch {
    return false;
  }
  try {
    if (typeof process.getuid === "function" && st.uid !== process.getuid()) return false;
  } catch {
    return false;
  }
  try {
    if ((st.mode & 0o077) !== 0) return false;
  } catch {
    return false;
  }
  return true;
}

/**
 * Ensure the context directory exists as a private directory: create with
 * mode 0700 when missing; when present, validate ownership/permissions
 * (fail closed) and repair lax modes with chmod 0700. Returns false on any
 * failure (fail open: the caller leaves the tool args unmutated).
 */
function ensurePrivateContextDir(dir: string): boolean {
  try {
    try {
      mkdirSync(dir, { recursive: true, mode: 0o700 });
      return true;
    } catch {
      // Exists already: validate before reuse.
    }
    if (!isSafeContextDir(dir)) return false;
    try {
      chmodSync(dir, 0o700);
    } catch {
      // Non-fatal: the mode check above already passed.
    }
    return true;
  } catch {
    return false;
  }
}

/**
 * Best-effort prune of stale vp-context-*.txt files older than the TTL.
 * Fail-open: every failure is swallowed so pruning never blocks the
 * handoff. Runs before each write so rejected or interrupted handoffs
 * cannot accumulate forever.
 */
function pruneStaleContextFiles(dir: string): void {
  var entries = null;
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  if (!entries) return;
  var now = Date.now();
  for (var i = 0; i < entries.length; i++) {
    var name = entries[i] || "";
    if (name.indexOf(CONTEXT_FILE_PREFIX) !== 0) continue;
    if (name.slice(-4) !== ".txt") continue;
    var full = join(dir, name);
    var age = -1;
    try {
      age = now - statSync(full).mtimeMs;
    } catch {
      continue;
    }
    if (age < 0 || age <= CONTEXT_FILE_TTL_MS) continue;
    try {
      rmSync(full, { force: true });
    } catch {
      // ignore: best-effort cleanup
    }
  }
}

/**
 * Persist context text to a 0600 tempfile for context-file handoff.
 * Returns the path, or null on any failure (fail open: the caller leaves
 * the tool args unmutated so the original command runs unchanged).
 */
async function writeContextFile(context: string): Promise<string | null> {
  if (!context) return null;
  if (Buffer.byteLength(context, "utf8") > CONTEXT_FILE_MAX_BYTES) return null;
  var dir = contextFileDir();
  try {
    if (!ensurePrivateContextDir(dir)) return null;
    pruneStaleContextFiles(dir);
    var fd = -1;
    var file = "";
    var attempts = 0;
    while (fd === -1 && attempts < 5) {
      attempts++;
      // 128-bit random entropy: unlinkable without directory listing,
      // unlike the prior timestamp+pid sequence.
      var name = CONTEXT_FILE_PREFIX + randomBytes(16).toString("hex") + ".txt";
      file = join(dir, name);
      try {
        // O_EXCL: fail when the path already exists instead of following
        // a pre-created symlink or overwriting another process's file.
        fd = openSync(file, "wx", 0o600);
      } catch {
        fd = -1;
        file = "";
      }
    }
    if (fd === -1 || !file) return null;
    try {
      writeFileSync(fd, context, { encoding: "utf8" });
    } finally {
      try {
        closeSync(fd);
      } catch {
        // ignore: descriptor cleanup is best-effort
      }
    }
    try {
      chmodSync(file, 0o600);
    } catch {
      // ignore: creation mode already requested 0600
    }
    return file;
  } catch {
    return null;
  }
}

/** Monotonic part id generator; opencode requires ids to start with "prt". */
let partCounter = 0;
function newPartId(): string {
  partCounter += 1;
  return "prt-vp-" + Date.now().toString(36) + "-" + partCounter + "-" + Math.random().toString(36).slice(2, 8);
}

async function handleChatMessage(
  input: { sessionID: string; messageID?: string },
  output: { message: { sessionID?: string }; parts: any[] },
  cwd: string,
): Promise<void> {
  // Idempotency guard: strip reminder parts injected by a previous run of
  // this hook before collecting text, so re-delivery never duplicates context.
  for (let i = output.parts.length - 1; i >= 0; i--) {
    const prior: any = output.parts[i];
    if (prior?.type === "text" && typeof prior.text === "string" && prior.text.startsWith(INJECTION_MARKER)) {
      output.parts.splice(i, 1);
    }
  }
  // Collect the user-visible text and resolve referenced image paths.
  const textChunks: string[] = [];
  for (const part of output.parts as any[]) {
    if (part?.type === "text" && typeof part.text === "string") {
      textChunks.push(part.text);
    }
  }
  const promptText = textChunks.join("\n");
  const images: string[] = [];
  for (const candidate of extractImagePaths(promptText)) {
    const resolvedPath = resolveImagePath(candidate, cwd);
    if (resolvedPath && isImagePath(resolvedPath) && existsSync(resolvedPath)) images.push(resolvedPath);
  }
  const uniqueImages = [...new Set(images)];
  if (uniqueImages.length === 0) return;
  // Reminder only: never shell out to vp analyze here. A slow or stuck
  // vision call used to delay message handling; the actual analysis happens
  // lazily in tool.execute.before when the model reads the image. Attached
  // image parts are left untouched so the model sees them natively.
  const anchor: any = output.parts[output.parts.length - 1];
  output.parts.push({
    id: newPartId(),
    sessionID: anchor?.sessionID ?? output.message?.sessionID ?? input.sessionID,
    messageID: anchor?.messageID ?? output.message?.id ?? input.messageID,
    type: "text",
    synthetic: true,
    text: readReminder(uniqueImages, INJECTION_MARKER, "message", "read"),
  });
}

async function handleToolExecuteBefore(
  input: { tool: string; sessionID?: string },
  output: { args: any },
  cwd: string,
  client?: unknown,
): Promise<void> {
  // Shell-tool rewrite path (U4): a model-invoked analyze command gets its
  // recent conversation context via a tempfile reference. The plugin writes
  // the session context it already fetches and mutates output.args.command
  // in place, so the model's own command executes with the reference.
  // Fail open: every failure returns with args unmutated so the original
  // command runs unchanged.
  if (input.tool === "bash" || input.tool === "shell") {
    var rawCommand =
      output.args && typeof output.args.command === "string" ? output.args.command : undefined;
    if (!rawCommand || !isUnflaggedAnalyzeCommand(rawCommand)) return;
    var shellContext = "";
    try {
      shellContext = await loadConversationContext(client, input.sessionID);
    } catch { /* fail open: no context */ }
    if (!shellContext) return;
    var contextPath = await writeContextFile(shellContext);
    if (!contextPath) return;
    output.args.command = appendContextFileArg(rawCommand, quoteShellArg(contextPath));
    return;
  }
  if (input.tool !== "read") return;
  const argPath =
    output.args && typeof output.args.path === "string"
      ? output.args.path
      : output.args && typeof output.args.filePath === "string"
        ? output.args.filePath
        : undefined;
  if (!isImagePath(argPath)) return;
  const filePath = resolveImagePath(argPath, cwd);
  if (!filePath || !existsSync(filePath)) return;
  // Ground the description in the recent conversation: fetch the session's
  // last user/assistant messages through the SDK client. Fail open: any
  // lookup failure simply means the analyze call runs without context.
  let context = "";
  try {
    context = await loadConversationContext(client, input.sessionID);
  } catch { /* fail open: no context */ }
  const description = await runAnalyze([filePath], context ? { context } : undefined);
  // Fail-open: when analysis is unavailable, allow the original read.
  if (!description) return;
  // Denying by throw surfaces this message to the model as the tool result,
  // which carries both the instruction and the description.
  throw new Error(withImageInstruction(description, INJECTION_MARKER));
}

export default async function visionProxyPlugin(input: {
  directory?: string;
  client?: unknown;
}): Promise<Hooks> {
  const pluginCwd = typeof input?.directory === "string" && input.directory ? input.directory : process.cwd();
  // The SDK client is what lets the read hook fetch the session's messages as
  // the analyze --context value; an install without it (or with a broken
  // client) degrades to context-free analysis rather than failing the read.
  const client = input?.client;
  return {
    "chat.message": async (innerInput, innerOutput) => {
      await handleChatMessage(innerInput as any, innerOutput as any, pluginCwd);
    },
    "tool.execute.before": async (innerInput, innerOutput) => {
      await handleToolExecuteBefore(innerInput as any, innerOutput as any, pluginCwd, client);
    },
  };
}
`;

export const OPENCODE_PLUGIN_SOURCE: string =
	OPENCODE_PLUGIN_HEADER + HOOK_RUNTIME_SOURCE + OPENCODE_PLUGIN_ADAPTER;
