/**
 * Embedded Pi extension source.
 *
 * `vp integration install pi` writes this exact TypeScript into Pi's global
 * extensions directory (`~/.pi/agent/extensions/vision-proxy_read.ts`). Pi auto-loads
 * it via its `jiti` loader, so it must run as plain TypeScript with no build step.
 *
 * The extension hooks into Pi's lifecycle events at parity with the Claude Code /
 * Codex hook script integration:
 *   - `input`: a no-op that returns immediately so the user's prompt is accepted
 *     and submitted the instant they press Enter. It never awaits `vp analyze`,
 *     so prompt submission is never blocked on the vision call.
 *   - `context`: fires right before Pi sends the turn's messages to the model.
 *     For each user message it finds image paths referenced in the text and
 *     appends a static reminder to inspect each one with the read tool. It
 *     never shells out to `vp analyze`, so it adds no latency: the actual
 *     analysis happens lazily in the `tool_result` handler when the model
 *     reads the image. Inline image attachments are left untouched so the
 *     model sees them natively.
 *   - `tool_result`: the single analysis point. Intercepts `read` tool results
 *     on image files and replaces the tool result content with the fenced
 *     UNTRUSTED description from `vp analyze` so no image bytes reach the model.
 *     The last user/assistant messages of the session branch are formatted
 *     into `vp analyze --context` (via `ctx.sessionManager.getBranch()`) so the
 *     description is grounded in the recent conversation.
 *
 * Pi fires the `input` event for every `session.prompt()` submission, including
 * ones that arrive while the agent is streaming and are queued via the
 * `streamingBehavior` option. Queued streaming prompts flow through the same
 * `context` reminder path, so no prompt submit is ever blocked.
 *
 * No tool is registered, keeping system tokens low.
 *
 * Fail-open: if `vp` is missing, exits non-zero, or any other error occurs, the
 * extension returns undefined and Pi proceeds unchanged. Image-derived text is
 * attacker-controlled, so the analyzer fence stays on.
 *
 * Composition: the shared analysis policy (path classification, env parsing,
 * reminder rendering, vp resolution) is inlined from the canonical runtime
 * (`src/integrations/runtime.ts`) at generate() time; the adapter below owns only
 * Pi lifecycle translation, mode gating, the async executor with AbortSignal
 * handling, and the tool_result output shape. The emitted file stays
 * standalone (no package import).
 *
 * NOTE: this module exports the extension source as a raw string. It uses
 * String.raw so regexes inside the generated source are written exactly once.
 * The generated source must therefore never contain a backtick or a dollar
 * sign followed by an opening brace.
 */
import { HOOK_RUNTIME_SOURCE } from "./runtime.ts";

// biome-ignore lint/complexity/noUselessStringRaw: String.raw keeps every composed chunk under the same embedding discipline so a future escape cannot silently interpolate.
const PI_EXTENSION_HEADER = String.raw`/**
 * vision-proxy Pi extension.
 *
 * Auto-generated by vp integration install pi. Do not edit by hand; re-run
 * the installer to regenerate after a vision-proxy upgrade.
 *
 * Hooks into Pi lifecycle events at parity with the Claude Code / Codex hook
 * script integration. No tool is registered.
 *
 * The context event, which fires right before the turn's messages are sent to
 * the model, appends a static reminder to read referenced image paths. It
 * never shells out, so the prompt submit stays instant: the user's text is
 * accepted the moment they press Enter and no vision call ever blocks it.
 * The input event is therefore a no-op. The tool_result event is the single
 * analysis point: it describes images the model actually reads.
 *
 * The description text returned by vp is attacker-controlled (it comes from
 * an external vision model), so it is forwarded verbatim inside its UNTRUSTED
 * fence and the consumer must treat it as untrusted input.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawn, spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { chmodSync, closeSync, existsSync, lstatSync, mkdirSync, openSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { homedir, tmpdir } from "node:os";

// __VP_VERSION__PLACEHOLDER__

`;

const PI_EXTENSION_ADAPTER = String.raw`
var TIMEOUT_MS = hookTimeoutMs(process.env.VP_HOOK_TIMEOUT_MS);

var CONTEXT_FILE_PREFIX = "vp-context-";
// Stale-file TTL: handoffs older than this are pruned before each write.
var CONTEXT_FILE_TTL_MS = 10 * 60 * 1000;

function contextFileDir(): string {
  var base = "";
  try {
    var tmp = process.env.TMPDIR || process.env.TMP || process.env.TEMP;
    if (tmp && tmp.trim()) base = tmp.trim();
  } catch {
    base = "";
  }
  if (!base) {
    try {
      base = tmpdir();
    } catch {
      base = "";
    }
  }
  if (!base) base = "/tmp";
  return join(base, "vision-proxy-context");
}

/**
 * True when an existing context directory is safe to reuse: not a symlink,
 * owned by the current user, and mode 0700 (no group/world access).
 * Fail-closed on any stat failure so callers abort rather than write into
 * an untrusted directory.
 */
function isSafeContextDir(dir: string): boolean {
  var st = null;
  try {
    st = lstatSync(dir);
  } catch {
    return false;
  }
  if (!st) return false;
  try {
    if (st.isSymbolicLink()) return false;
  } catch {
    return false;
  }
  try {
    if (typeof process.getuid === "function" && st.uid !== process.getuid()) return false;
  } catch {
    return false;
  }
  try {
    if ((st.mode & 0o077) !== 0) return false;
  } catch {
    return false;
  }
  return true;
}

/**
 * Ensure the context directory exists as a private directory: create with
 * mode 0700 when missing; when present, validate ownership/permissions
 * (fail closed) and repair lax modes with chmod 0700. Returns false on any
 * failure (fail open: the caller leaves the tool input unmutated).
 */
function ensurePrivateContextDir(dir: string): boolean {
  try {
    try {
      mkdirSync(dir, { recursive: true, mode: 0o700 });
      return true;
    } catch {
      // Exists already: validate before reuse.
    }
    if (!isSafeContextDir(dir)) return false;
    try {
      chmodSync(dir, 0o700);
    } catch {
      // Non-fatal: the mode check above already passed.
    }
    return true;
  } catch {
    return false;
  }
}

/**
 * Best-effort prune of stale vp-context-*.txt files older than the TTL.
 * Fail-open: every failure is swallowed so pruning never blocks the
 * handoff. Runs before each write so rejected or interrupted handoffs
 * cannot accumulate forever.
 */
function pruneStaleContextFiles(dir: string): void {
  var entries = null;
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  if (!entries) return;
  var now = Date.now();
  for (var i = 0; i < entries.length; i++) {
    var name = entries[i] || "";
    if (name.indexOf(CONTEXT_FILE_PREFIX) !== 0) continue;
    if (name.slice(-4) !== ".txt") continue;
    var full = join(dir, name);
    var age = -1;
    try {
      age = now - statSync(full).mtimeMs;
    } catch {
      continue;
    }
    if (age < 0 || age <= CONTEXT_FILE_TTL_MS) continue;
    try {
      rmSync(full, { force: true });
    } catch {
      // ignore: best-effort cleanup
    }
  }
}

/**
 * Persist context text to a 0600 tempfile for context-file handoff.
 * Returns the path, or null on any failure (fail open: the caller leaves
 * the tool input unmutated so the original command runs unchanged).
 */
function writeContextFile(context: string): string | null {
  if (!context) return null;
  if (typeof Buffer !== "undefined" && Buffer.byteLength(context, "utf8") > CONTEXT_FILE_MAX_BYTES) return null;
  var dir = contextFileDir();
  try {
    if (!ensurePrivateContextDir(dir)) return null;
    pruneStaleContextFiles(dir);
    var fd = -1;
    var file = "";
    var attempts = 0;
    while (fd === -1 && attempts < 5) {
      attempts++;
      // 128-bit random entropy: unlinkable without directory listing.
      // Pi may run without process.pid, so no pid component is assumed.
      var name = CONTEXT_FILE_PREFIX + randomBytes(16).toString("hex") + ".txt";
      file = join(dir, name);
      try {
        // O_EXCL: fail when the path already exists instead of following
        // a pre-created symlink or overwriting another process's file.
        fd = openSync(file, "wx", 0o600);
      } catch {
        fd = -1;
        file = "";
      }
    }
    if (fd === -1 || !file) return null;
    try {
      writeFileSync(fd, context, { encoding: "utf8" });
    } finally {
      try {
        closeSync(fd);
      } catch {
        // ignore: descriptor cleanup is best-effort
      }
    }
    try {
      chmodSync(file, 0o600);
    } catch {
      // ignore: creation mode already requested 0600
    }
    return file;
  } catch {
    return null;
  }
}

/** Session-branch messages formatted for the analyze context value.
 * Shared by the tool_result read path and the tool_call rewrite path:
 * maps session entries to the plain shape the formatter expects, strips
 * our own reminder blocks, and fails open to "" on any shape error. */
function sessionBranchContext(ctx: unknown): string {
  try {
    var branch = ctx && (ctx as any).sessionManager ? (ctx as any).sessionManager.getBranch() : null;
    var msgs = (Array.isArray(branch) ? branch : [])
      .filter((e) => e && e.type === "message" && e.message)
      .map((e) => {
        var c = e.message.content;
        if (Array.isArray(c)) {
          c = c.filter(function (b) {
            return !(b && b.type === "text" && typeof b.text === "string" && b.text.indexOf(REMINDER_MARKER) === 0);
          });
        }
        return { role: e.message.role, content: c };
      });
    return buildConversationContext(msgs);
  } catch { return ""; }
}

/** Run vp analyze (async) and return the fenced description, or null on failure.
 * The optional extras (question, context) travel on stdin, never argv, so the
 * description is grounded in the recent conversation without exposing it in
 * the process listing. */
async function runAnalyze(images: string[], extras, signal?: unknown): Promise<string | null> {
  return new Promise((resolve) => {
    if (!images || images.length === 0) return resolve(null);
    var maxTokens = maxOutputTokens(process.env.VP_MAX_OUTPUT_TOKENS);
    var invocation = buildAnalyzeArgs(images, maxTokens, extras);
    var command = invocation.command;
    var args = invocation.args;
    // Sensitive text travels on stdin (CWE-214), like the stdio hook and the
    // opencode plugin. Nothing sensitive is appended to the command line.
    var stdinText = invocation.stdin;
    var vp = resolveVpBin();
    let settled = false;
    let timer: unknown = null;
    const finish = (val: string | null) => {
      if (settled) return;
      settled = true;
      if (timer) clearTimeout(timer as NodeJS.Timeout);
      resolve(val);
    };
    let child;
    try {
      child = spawn(command, args);
      // A child that exits before stdin drains raises EPIPE asynchronously
      // on the stdin stream (the process 'error' event below does not cover
      // it), which without a listener is an uncaught exception that can
      // crash the host. Register the guard BEFORE write/end so every
      // delivery path is covered; the process error/close handlers settle
      // the promise either way.
      child.stdin.on("error", () => { /* error/close handlers settle */ });
      if (stdinText) {
        try { child.stdin.write(stdinText); } catch { /* error handler settles */ }
      }
      try { child.stdin.end(); } catch { /* error handler settles */ }
    } catch (err) {
      const msg = err && (err as Error).message ? (err as Error).message : String(err);
      process.stderr.write("[vision-proxy] failed to spawn vp: " + msg + "\n");
      return resolve(null);
    }
    let stdout = "";
    child.stdout.on("data", (d) => { stdout += String(d); });
    child.stderr.on("data", (d) => { process.stderr.write(String(d)); });
    child.on("error", (err) => {
      const e = err as NodeJS.ErrnoException;
      if (e && e.code === "ENOENT") process.stderr.write("[vision-proxy] vp binary not found: " + vp + "\n");
      else process.stderr.write("[vision-proxy] vp analyze failed: " + (e && e.message ? e.message : String(err)) + "\n");
      finish(null);
    });
    child.on("close", (code) => {
      const out = stdout.trim();
      if (code !== 0 || !out) {
        process.stderr.write("[vision-proxy] vp analyze exited with status " + (code == null ? "?" : String(code)) + "\n");
        finish(null);
      } else {
        finish(out.trimEnd());
      }
    });
    timer = setTimeout(() => {
      try { if (child) child.kill("SIGKILL"); } catch { /* ignore */ }
      process.stderr.write("[vision-proxy] vp analyze timed out\n");
      finish(null);
    }, TIMEOUT_MS);
    if (signal && (signal as AbortSignal).addEventListener) {
      const onAbort = () => {
        // Settle immediately so the context handler does not hang until the hard
        // timeout waiting on a child that swallows SIGTERM and never emits "close".
        finish(null);
        try { if (child) child.kill("SIGTERM"); } catch { /* ignore */ }
        // Force-stop a child that handles SIGTERM and never exits.
        try {
          const dying = child;
          setTimeout(() => { try { if (dying) dying.kill("SIGKILL"); } catch { /* ignore */ } }, 1000);
        } catch { /* ignore */ }
      };
      if ((signal as AbortSignal).aborted) onAbort();
      else (signal as AbortSignal).addEventListener("abort", onAbort, { once: true });
    }
  });
}

// Cache the config-derived mode for the process lifetime. Resolving it spawns a
// vp config get --json subprocess, which is wasteful to repeat on every event.
let cachedConfigMode: "always" | "off" | null = null;

/** Read mode from VP_MODE (honored live) or vp config get --json (cached). Returns "always" | "off". */
function getMode(): "always" | "off" {
  // VP_MODE is a cheap, runtime-overridable env var; always honor it live so a
  // session can switch modes without restarting.
  const envMode = process.env.VP_MODE;
  if (envMode === "always" || envMode === "off") return envMode;
  if (cachedConfigMode) return cachedConfigMode;
  let mode: "always" | "off" = "always";
  try {
    const vp = resolveVpBin();
    const { command, args: prefix } = vpEntryToSpawn(vp);
    const result = spawnSync(command, [...prefix, "config", "get", "--json"], {
      encoding: "utf8",
      timeout: 5000,
      maxBuffer: 1024 * 1024,
    });
    if (!result.error && result.status === 0 && result.stdout.trim()) {
      const cfg = JSON.parse(result.stdout);
      const resolved = cfg.mode as string | undefined;
      if (resolved === "always" || resolved === "off") mode = resolved;
    }
  } catch {
    // fall through to the default
  }
  cachedConfigMode = mode;
  return mode;
}

export default function setup(pi: ExtensionAPI): void {
  // --- input: keep prompt submit instant; the context event only appends text ---
  pi.on("input", async (_event) => {
    // Intentionally a no-op. Returning undefined immediately lets Pi accept and
    // submit the user's prompt with zero blocking work. The reminder is appended
    // later in the context event (which fires right before the messages are
    // sent to the model), so prompt submission is never delayed by any lookup
    // or vision call.
    return undefined;
  });

  // --- context: append a static reminder to read referenced image paths ---
  pi.on("context", async (event) => {
    if (getMode() === "off") return undefined;
    const messages = Array.isArray(event.messages) ? event.messages : null;
    if (!messages) return undefined;

    let modified = false;
    const out: unknown[] = [];
    for (const msg of messages) {
      if (!msg || (msg as any).role !== "user" || !Array.isArray((msg as any).content)) {
        out.push(msg);
        continue;
      }
      const content = (msg as any).content as Array<any>;
      // Idempotency guard: strip reminders injected by a previous run of this
      // handler before collecting paths, so re-delivery (Pi re-fires context
      // for every model call) never stacks duplicate reminder text. Matching
      // is by marker prefix: user text starting with our internal marker is
      // treated as ours (the marker is never user-facing; typing it verbatim
      // is the only false positive, and is accepted as user error).
      const fresh = content.filter(
        (c) => !(c && c.type === "text" && typeof c.text === "string" && c.text.indexOf(REMINDER_MARKER) === 0),
      );
      const seen = new Set<string>();
      const paths: string[] = [];
      for (const c of fresh) {
        if (c && c.type === "text" && typeof c.text === "string") {
          const found = extractImagePaths(c.text)
            .map((p) => resolveImagePath(p, process.cwd()))
            .filter((p): p is string => !!p && isImagePath(p) && existsSync(p));
          for (const p of found) {
            if (!seen.has(p)) {
              seen.add(p);
              paths.push(p);
            }
          }
        }
      }
      if (paths.length === 0) {
        // Remove a reminder from a prior context pass even when its image has
        // disappeared since then; otherwise the model keeps a stale path.
        if (fresh.length !== content.length) {
          modified = true;
          out.push({ ...(msg as any), content: fresh });
        } else {
          out.push(msg);
        }
        continue;
      }
      // Reminder only: never shell out to vp analyze here. A slow or stuck
      // vision call used to delay every model send; the actual analysis happens
      // lazily in the tool_result handler when the model reads the image.
      // Inline image attachments are left untouched so the model sees them natively.
      modified = true;
      out.push({
        ...(msg as any),
        content: [...fresh, { type: "text", text: readReminder(paths, REMINDER_MARKER, "message", "read") }],
      });
    }
    if (modified) return { messages: out };
    return undefined;
  });

  // --- tool_call: append a context-file reference to model-invoked analyze ---
  // Fires before the tool executes; event.input is mutable, so appending
  // --context-file here rewrites the model's own bash command in place and
  // it executes with the reference (no deny, no substitute). Fail open:
  // every failure returns undefined with input unmutated so the original
  // command runs unchanged.
  pi.on("tool_call", async (event, ctx) => {
    if (getMode() === "off") return undefined;
    if (!event || (event as any).toolName !== "bash") return undefined;
    var input = (event as any).input;
    if (!input || typeof input.command !== "string") return undefined;
    if (!isUnflaggedAnalyzeCommand(input.command)) return undefined;
    var toolContext = sessionBranchContext(ctx);
    if (!toolContext) return undefined;
    var toolContextPath = writeContextFile(toolContext);
    if (!toolContextPath) return undefined;
    input.command = appendContextFileArg(input.command, quoteShellArg(toolContextPath));
    return undefined;
  });

  // --- tool_result: replace read results on image files ---
  pi.on("tool_result", async (event, ctx) => {
    if (event.toolName !== "read") return undefined;
    const argPath = event.input && typeof event.input.path === "string" ? event.input.path : undefined;
    if (!isImagePath(argPath)) return undefined;
    if (getMode() === "off") return undefined;
    const filePath = resolveImagePath(argPath, process.cwd());
    if (!filePath || !existsSync(filePath)) return undefined;
    var context = sessionBranchContext(ctx);
    const description = await runAnalyze(
      [filePath],
      context ? { context } : undefined,
      ctx && (ctx as any).signal ? (ctx as any).signal : undefined,
    );
    if (!description) return undefined; // fail-open
    return { content: [{ type: "text", text: withImageInstruction(description, undefined) }] };
  });
}
`;

export const PI_EXTENSION_SOURCE: string =
	PI_EXTENSION_HEADER + HOOK_RUNTIME_SOURCE + PI_EXTENSION_ADAPTER;
