/**
 * Embedded agent hook script source.
 *
 * `vp integration install claude-code` writes this exact TypeScript to
 * `~/.claude/hooks/vision-proxy.ts`, and `vp integration install codex`
 * writes it to `~/.codex/hooks/vision-proxy.ts`. Each host registers its
 * copy as a plain command (`npx tsx <path>`) in its hooks config, so the
 * config carries only standard keys (type, command, timeout, matcher) and
 * no vision-proxy metadata. The installed file carries a version marker
 * comment so `vp integration status` can report staleness.
 *
 * The script handles both hook events: UserPromptSubmit emits a static Read reminder for prompt image
 * paths plus pasted/attached image refs resolved via the image cache (never
 * shells out, so prompt submission is never blocked), and PreToolUse Read or
 * view_image (image path reads) shells out to `vp analyze` and emits
 * hookSpecificOutput.additionalContext with a deny decision. Fail-open: on any
 * error it exits 0 with no stdout so the agent proceeds unchanged.
 *
 * Composition: the shared analysis policy (path classification, env parsing,
 * reminder rendering, vp resolution) is inlined from the canonical runtime
 * (`src/hooks/runtime.ts`) at generate() time; the adapter below owns only
 * stdio event translation, image-cache refs, the sync executor, and the
 * deny/output shapes. The emitted file stays standalone (no package import).
 *
 * NOTE: this module exports the script source as a raw string. It uses
 * String.raw so regexes inside the generated source are written exactly once.
 * The generated source must therefore never contain a backtick or a dollar
 * sign followed by an opening brace.
 */
import { HOOK_RUNTIME_SOURCE } from "./hooks/runtime.ts";

// biome-ignore lint/complexity/noUselessStringRaw: String.raw keeps every composed chunk under the same embedding discipline so a future escape cannot silently interpolate.
const HOOK_SCRIPT_HEADER = String.raw`#!/usr/bin/env -S npx tsx
/**
 * vision-proxy agent hook script.
 *
 * Auto-generated by vp integration install. Do not edit by hand; re-run
 * the installer to regenerate after a vision-proxy upgrade.
 *
 * Prerequisite: tsx must be installed for the host npx tsx command to
 * run this file (e.g. npm install -g tsx).
 *
 * Handles UserPromptSubmit and PreToolUse events: UserPromptSubmit emits
 * a static Read reminder for prompt image paths and pasted or attached
 * image refs resolved via the image cache (never shells out, so prompt
 * submission is never blocked), while PreToolUse analyzes Read-tool or
 * view_image image paths by shelling out to vp analyze, then emits
 * hookSpecificOutput.additionalContext with a deny decision for the agent.
 *
 * Fail-open: on any error it exits 0 with no stdout, so the agent proceeds
 * unchanged. Image-derived text is attacker-controlled, so the analyzer
 * fence stays on.
 */

// __VP_VERSION__PLACEHOLDER__

import { spawnSync } from "node:child_process";
import {
  chmodSync,
  closeSync,
  existsSync,
  fstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  readdirSync,
  readSync,
  realpathSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join, resolve, sep } from "node:path";

`;

const HOOK_SCRIPT_ADAPTER = String.raw`
var IMAGE_REF_RE = /\[Image #(\d+)\]/g;

function claudeConfigHome(): string {
  var override = process.env.VP_CLAUDE_CONFIG_DIR || process.env.CLAUDE_CONFIG_DIR;
  if (override && override.trim()) return resolve(override.trim());
  var home = process.env.HOME || homedir();
  return join(home, ".claude");
}

function imageCacheDir(): string {
  return join(claudeConfigHome(), "image-cache");
}

function isSafeSessionId(sessionId: unknown): sessionId is string {
  return typeof sessionId === "string" && /^[A-Za-z0-9_-]+$/.test(sessionId);
}

function resolveImageRefs(prompt: string, sessionId: string | undefined): string[] {
  var paths: string[] = [];
  var seen: string[] = [];
  if (!isSafeSessionId(sessionId)) return paths;
  var sessionDir = join(imageCacheDir(), sessionId);
  if (!existsSync(sessionDir)) return paths;
  IMAGE_REF_RE.lastIndex = 0;
  var m: RegExpExecArray | null;
  while ((m = IMAGE_REF_RE.exec(prompt)) !== null) {
    var id = Number(m[1]);
    if (!isFinite(id)) continue;
    for (var i = 0; i < IMAGE_EXT.length; i++) {
      var candidate = join(sessionDir, String(id) + "." + IMAGE_EXT[i]);
      if (existsSync(candidate)) {
        if (seen.indexOf(candidate) === -1) {
          seen.push(candidate);
          paths.push(candidate);
        }
        break;
      }
    }
  }
  return paths;
}

function readEvent(): Record<string, any> | null {
  var raw: string;
  try {
    raw = readFileSync(0, "utf8");
  } catch (e) {
    process.stderr.write("[vision-proxy] could not read hook event from stdin\n");
    return null;
  }
  try {
    return JSON.parse(raw);
  } catch (e) {
    process.stderr.write("[vision-proxy] hook event on stdin was not valid JSON\n");
    return null;
  }
}

function readToolInput(event: Record<string, any>): Record<string, any> {
  if (event.tool_input != null && typeof event.tool_input === "object") return event.tool_input;
  if (event.toolInput != null && typeof event.toolInput === "object") return event.toolInput;
  return {};
}

function readToolFilePath(event: Record<string, any>): string | null {
  var toolName = event.tool_name != null ? event.tool_name : event.toolName;
  if (toolName !== "Read" && toolName !== "view_image") return null;
  var toolInput = readToolInput(event);
  var file = toolName === "view_image"
    ? (toolInput.path != null ? toolInput.path : toolInput.file_path)
    : (toolInput.file_path != null ? toolInput.file_path : toolInput.path);
  if (!isImagePath(file)) return null;
  var cwd = typeof event.cwd === "string" ? event.cwd : undefined;
  return resolveImagePath(file, cwd);
}

function promptCacheFile(sessionId: string): string | null {
  if (!isSafeSessionId(sessionId)) return null;
  return join(imageCacheDir(), sessionId, "vp-prompt.txt");
}

function writePromptCache(sessionId: string | undefined, prompt: string, turnId?: string): void {
  // Side-channel for --question: UserPromptSubmit writes the current prompt so
  // later PreToolUse events in the same turn can read it back. Latest wins.
  try {
    if (!isSafeSessionId(sessionId)) return;
    prunePromptCache();
    var file = promptCacheFile(sessionId);
    if (!file) return;
    var normalized = prompt.trim();
    if (!normalized) {
      try { unlinkSync(file); } catch { /* no stale question is harmless */ }
      return;
    }
    mkdirSync(join(imageCacheDir(), sessionId), { recursive: true });
    var truncated = normalized.length > QUESTION_MAX_CHARS;
    var stored = truncated ? "…" + normalized.slice(-QUESTION_MAX_CHARS + 1) : normalized;
    writeFileSync(file, JSON.stringify({ turnId: turnId || null, prompt: stored }), { mode: 0o600 });
    chmodSync(file, 0o600);
  } catch (e) {
    process.stderr.write("[vision-proxy] prompt cache write failed open: " + String(e) + "\n");
  }
}

var lastPromptPruneAt = 0;

function prunePromptCache(): void {
  // Prompt files can outlive a turn when no image read follows it. Prune old
  // entries opportunistically on the next prompt without touching image files.
  try {
    var now = Date.now();
    if (now - lastPromptPruneAt < 60000) return;
    lastPromptPruneAt = now;
    var dir = imageCacheDir();
    if (!existsSync(dir)) return;
    var entries = readdirSync(dir, { withFileTypes: true });
    for (var i = 0; i < entries.length; i++) {
      var entry = entries[i];
      if (!entry || !entry.isDirectory()) continue;
      var file = join(dir, entry.name, "vp-prompt.txt");
      try {
        var age = now - statSync(file).mtimeMs;
        if (age > 24 * 60 * 60 * 1000) unlinkSync(file);
      } catch { /* stale or concurrently removed entries are harmless */ }
    }
  } catch (e) {
    process.stderr.write("[vision-proxy] prompt cache prune failed open: " + String(e) + "\n");
  }
}

function readPromptCache(sessionId: string | undefined, turnId?: string): string | null {
  // Keep the prompt through all image reads in a turn; the next submit replaces
  // it, and an empty submit clears it.
  try {
    if (!isSafeSessionId(sessionId)) return null;
    var file = promptCacheFile(sessionId);
    if (!file || !existsSync(file)) return null;
    var raw = readFileSync(file, "utf8").trim();
    var text = raw;
    try {
      var parsed = JSON.parse(raw);
      if (parsed && typeof parsed.prompt === "string") {
        if (parsed.turnId && turnId && parsed.turnId !== turnId) {
          unlinkSync(file);
          return null;
        }
        text = parsed.prompt;
      }
    } catch { /* legacy raw prompt format remains readable */ }
    return text ? text : null;
  } catch (e) {
    process.stderr.write("[vision-proxy] prompt cache read failed open: " + String(e) + "\n");
    return null;
  }
}

function trustedTranscriptPath(transcriptPath: string): string | null {
  try {
    var candidate = realpathSync(resolve(transcriptPath));
    var home = process.env.HOME || homedir();
    var roots = [claudeConfigHome(), join(home, ".codex")];
    for (var i = 0; i < roots.length; i++) {
      try {
        var root = realpathSync(resolve(roots[i]));
        if (candidate === root || candidate.indexOf(root + sep) === 0) return candidate;
      } catch { /* an uninstalled host directory is not a trusted root */ }
    }
  } catch { /* invalid, missing, or symlinked-out paths fail closed */ }
  return null;
}

const TRANSCRIPT_MAX_BYTES = 65536;
const TRANSCRIPT_MAX_LINES = 200;
const QUESTION_MAX_CHARS = 12000;

function readTranscriptTail(transcriptPath: string): string {
  var fd = openSync(transcriptPath, "r");
  try {
    var size = fstatSync(fd);
    if (!size.isFile()) return "";
    var start = Math.max(0, size.size - TRANSCRIPT_MAX_BYTES);
    var buffer = Buffer.alloc(size.size - start);
    var bytes = 0;
    while (bytes < buffer.length) {
      var n = readSync(fd, buffer, bytes, buffer.length - bytes, start + bytes);
      if (n <= 0) break;
      bytes += n;
    }
    return buffer.subarray(0, bytes).toString("utf8");
  } finally {
    closeSync(fd);
  }
}

function extractTranscriptContext(transcriptPath: unknown, question?: string | null): string | null {
  // Bounded tail parse of the session JSONL transcript for --context: only the
  // last 64KB / last 200 lines is read, user|assistant entries are shaped into
  // the shared buildConversationContext window, and the current user turn is
  // omitted when it is already being passed separately as --question.
  try {
    if (!includeContextEnabled(process.env)) return null;
    if (typeof transcriptPath !== "string" || !transcriptPath) return null;
    var trustedPath = trustedTranscriptPath(transcriptPath);
    if (!trustedPath) return null;
    var raw = readTranscriptTail(trustedPath);
    var lines = raw.split("\n");
    if (lines.length > TRANSCRIPT_MAX_LINES) lines = lines.slice(-TRANSCRIPT_MAX_LINES);
    var messages: Array<{ role: string; content: unknown }> = [];
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      if (!line) continue;
      line = line.trim();
      if (!line) continue;
      var entry: Record<string, any>;
      try { entry = JSON.parse(line); } catch { continue; }
      if (!entry || typeof entry !== "object") continue;
      if (entry.type !== "user" && entry.type !== "assistant") continue;
      var msg = entry.message != null && typeof entry.message === "object" ? entry.message : null;
      var role = msg && typeof msg.role === "string" ? msg.role : entry.type;
      if (role !== "user" && role !== "assistant") continue;
      messages.push({ role: role, content: msg ? msg.content : null });
    }
    if (question && messages.length > 0) {
      var last = messages[messages.length - 1]!;
      var lastText = extractMessageText(last.content).trim();
      var normalizedQuestion = question.trim();
      var matchesFull = lastText === normalizedQuestion;
      var matchesTail = normalizedQuestion.indexOf("…") === 0 &&
        lastText.endsWith(normalizedQuestion.slice(1));
      if (last.role === "user" && (matchesFull || matchesTail)) messages.pop();
    }
    var built = buildConversationContext(messages);
    return built ? built : null;
  } catch (e) {
    process.stderr.write("[vision-proxy] transcript context failed open: " + String(e) + "\n");
    return null;
  }
}

function runAnalyze(images: string[], question?: string | null, context?: string | null): string | null {
  if (!images || images.length === 0) return null;
  var timeout = hookTimeoutMs(process.env.VP_HOOK_TIMEOUT_MS);
  var maxTokens = maxOutputTokens(process.env.VP_MAX_OUTPUT_TOKENS);
  var invocation = buildAnalyzeStdinInvocation(images, maxTokens, question ? question : undefined, context ? context : undefined);
  var vp = resolveVpBin();
  var result = spawnSync(invocation.command, invocation.args, {
    encoding: "utf8",
    timeout: timeout,
    maxBuffer: MAX_BUFFER_BYTES,
    input: invocation.stdin,
  }) as { error?: NodeJS.ErrnoException; status?: number | null; stdout?: unknown };
  if (result.error) {
    if (result.error.code === "ENOENT") {
      process.stderr.write("[vision-proxy] vp binary not found: " + vp + "\n");
    } else {
      process.stderr.write("[vision-proxy] vp analyze failed or timed out\n");
    }
    return null;
  }
  var out = String(result.stdout == null ? "" : result.stdout).trim();
  if (result.status !== 0 || !out) {
    process.stderr.write("[vision-proxy] vp analyze exited with status " + String(result.status == null ? "?" : result.status) + "\n");
    return null;
  }
  return out;
}

function emit(eventName: string, description: string, permissionDecision?: string): void {
  var hookSpecificOutput: Record<string, unknown> = {
    hookEventName: eventName,
    additionalContext: description,
  };
  if (permissionDecision) {
    hookSpecificOutput.permissionDecision = permissionDecision;
    hookSpecificOutput.permissionDecisionReason = "Image read intercepted by vision-proxy; see additionalContext for the description.";
  }
  process.stdout.write(JSON.stringify({ hookSpecificOutput: hookSpecificOutput }) + "\n");
}

function runHook(event: Record<string, any> | null): void {
  if (!event) return;
  var eventName = event.hook_event_name != null ? event.hook_event_name : event.hookEventName;
  if (eventName === "UserPromptSubmit") {
    var prompt = typeof event.prompt === "string" ? event.prompt : "";
    var sessionId = event.session_id != null ? event.session_id : event.sessionId;
    var turnId = event.turn_id != null ? event.turn_id : event.turnId;
    writePromptCache(
      typeof sessionId === "string" ? sessionId : undefined,
      prompt,
      typeof turnId === "string" ? turnId : undefined,
    );
    var images = extractImagePaths(prompt);
    var refImages = resolveImageRefs(prompt, typeof sessionId === "string" ? sessionId : undefined);
    var allImages = images.concat(refImages);
    if (allImages.length === 0) return;
    emit("UserPromptSubmit", readReminder(allImages, undefined, "prompt", "Read"));
    return;
  }
  if (eventName === "PreToolUse") {
    var file = readToolFilePath(event);
    if (!file) return;
    var preSessionId = event.session_id != null ? event.session_id : event.sessionId;
    var preTurnId = event.turn_id != null ? event.turn_id : event.turnId;
    var question = readPromptCache(
      typeof preSessionId === "string" ? preSessionId : undefined,
      typeof preTurnId === "string" ? preTurnId : undefined,
    );
    var transcriptPath = event.transcript_path != null ? event.transcript_path : event.transcriptPath;
    var context = extractTranscriptContext(transcriptPath, question);
    var desc = runAnalyze([file], question, context);
    if (!desc) return;
    var toolName = event.tool_name != null ? event.tool_name : event.toolName;
    emit("PreToolUse", withImageInstruction(desc, undefined, toolName === "view_image" ? "view_image" : "Read"), "deny");
    return;
  }
}

try {
  runHook(readEvent());
} catch (e) {
  process.stderr.write("[vision-proxy] hook failed open: " + String(e) + "\n");
}
`;

export const HOOK_SCRIPT_SOURCE: string =
	HOOK_SCRIPT_HEADER + HOOK_RUNTIME_SOURCE + HOOK_SCRIPT_ADAPTER;
