/**
 * Embedded opencode v1 plugin source.
 *
 * `vp integration install opencode` writes this exact TypeScript into
 * `~/.config/opencode/plugins/vision-proxy.ts`. opencode auto-loads it via its
 * TypeScript loader (jiti/tsx), so it must run as plain TypeScript with no
 * build step.
 *
 * The plugin registers hooks for strict parity with claude-code/codex:
 * - `chat.message` - extracts image paths from user prompt, runs `vp analyze`,
 *   emits description as additional context (like UserPromptSubmit)
 * - `tool.execute.before` - intercepts `Read` tool calls on image files,
 *   runs `vp analyze`, emits description as additional context, denies the Read
 *   (like PreToolUse Read)
 *
 * No new `analyze_image` tool is registered - the agent uses its native Read
 * tool, which the hook intercepts and replaces with vision-proxy description.
 *
 * Fail-open: if `vp` is missing or exits non-zero, the hook logs and allows
 * the original tool call to proceed.
 */
export const OPENCODE_PLUGIN_SOURCE = `/**
 * vision-proxy opencode plugin.
 *
 * Auto-generated by \`vp integration install opencode\`. Do not edit by hand;
 * re-run the installer to regenerate after a vision-proxy upgrade.
 *
 * Registers hooks for strict parity with claude-code/codex:
 * - chat.message -> like UserPromptSubmit
 * - tool.execute.before (Read) -> like PreToolUse Read
 *
 * No new analyze_image tool - agent uses native Read which hook intercepts.
 */
import type { Hooks } from "@opencode-ai/plugin";
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

// __VP_VERSION__PLACEHOLDER__

const IMAGE_EXT = ["jpg", "jpeg", "png", "gif", "webp", "bmp", "tiff", "tif", "ico", "avif"];
const MAX_BUFFER_BYTES = 10 * 1024 * 1024;
const TIMEOUT_MS = Number(process.env.VP_HOOK_TIMEOUT_MS ?? 30000);

function vpEntryToSpawn(cmd: string): { command: string; args: string[] } {
  if (/\\.js$/i.test(cmd)) return { command: process.execPath, args: [cmd] };
  return { command: cmd, args: [] };
}

function resolveVpBin(): string {
  const env = process.env.VP_BIN;
  if (env?.trim()) return env;
  return "vp";
}

function isImagePath(p: string | undefined | null): boolean {
  if (!p || typeof p !== "string") return false;
  const ext = p.split(".").pop()?.toLowerCase();
  return !!ext && IMAGE_EXT.includes(ext);
}

const CLAUDE_CONFIG_ENV = "CLAUDE_CONFIG_DIR";
const CLAUDE_CONFIG_DIR_ENV = "VP_CLAUDE_CONFIG_DIR";

function claudeConfigHome(): string {
  const override = process.env[CLAUDE_CONFIG_DIR_ENV] || process.env[CLAUDE_CONFIG_ENV];
  if (override?.trim()) return resolve(override.trim());
  return join(homedir(), ".claude");
}

function imageCacheDir(): string {
  return join(claudeConfigHome(), "image-cache");
}

const IMAGE_REF_RE = /\\[Image #(\\d+)\\]/g;

function resolveImageRefs(prompt: string, sessionId: string | undefined): string[] {
  const paths: string[] = [];
  const seen = new Set<string>();
  if (!sessionId) return paths;
  if (sessionId.includes("/") || sessionId.includes("\\\\") || sessionId.includes("..") || sessionId === "." || sessionId.trim() === "") return paths;
  const sessionDir = join(imageCacheDir(), sessionId);
  if (!existsSync(sessionDir)) return paths;
  for (const m of prompt.matchAll(IMAGE_REF_RE)) {
    const id = Number(m[1]);
    if (!Number.isFinite(id)) continue;
    for (const ext of IMAGE_EXT) {
      const candidate = join(sessionDir, \`\${id}.\${ext}\`);
      if (existsSync(candidate)) {
        if (!seen.has(candidate)) { seen.add(candidate); paths.push(candidate); }
        break;
      }
    }
  }
  return paths;
}

function extractImagePaths(text: string): string[] {
  const paths = new Set<string>();
  const add = (p: string) => { const t = (p || "").trim(); if (t) paths.add(t); };
  const re1 = /(?:^[\\s"'])([a-zA-Z]:[/\\\\][^\\s"'*?|]*?pi-clipboard-[a-f0-9-]+\\.[a-zA-Z0-9]+|\\/[^\\s"'*?|]*?pi-clipboard-[a-f0-9-]+\\.[a-zA-Z0-9]+)/gim;
  for (const m of text.matchAll(re1)) add(m[1]);
  const extPattern = IMAGE_EXT.join("|");
  const re2 = new RegExp(\`(?:^|[\\\\s"'(])((?:[a-zA-Z]:[/\\\\\\\\]|/|~)[^"'*?|\\\\n]*?[/\\\\\\\\][^"'*?|\\\\n]*?\\\\.(?:${extPattern}))\\\\b\`, "gi");
  for (const m of text.matchAll(re2)) add(m[1]);
  const re3 = new RegExp(\`(?:^|[\\\\s"'(])(\\\\.\\\\.?/[^"'*?|\\\\n]*?\\\\.(?:${extPattern}))\\\\b\`, "gi");
  for (const m of text.matchAll(re3)) add(m[1]);
  return [...paths];
}

function resolveImagePath(p: string | undefined | null, cwd?: string): string | null {
  if (!p) return null;
  if (p.startsWith("/") || p.startsWith("~") || /^[a-zA-Z]:[/\\\\]/.test(p)) return p;
  if (cwd && (p.startsWith("./") || p.startsWith("../"))) {
    try { return resolve(cwd, p); } catch { return p; }
  }
  return p;
}

function runAnalyze(images: string[], question?: string): string | null {
  if (images.length === 0) return null;
  const vp = resolveVpBin();
  const { command, args: prefix } = vpEntryToSpawn(vp);
  const codexCap = Number(process.env.VP_MAX_OUTPUT_TOKENS ?? 2000);
  const args = [...prefix, "analyze", ...images, "--max-output-tokens", String(codexCap)];
  if (question?.trim()) args.push("--question", question.trim());
  const result = spawnSync(command, args, { encoding: "utf8", timeout: TIMEOUT_MS, maxBuffer: MAX_BUFFER_BYTES });
  if (result.error) {
    if ((result.error as NodeJS.ErrnoException).code === "ENOENT") {
      console.error(\`[vision-proxy] vp binary not found: \${vp}\`);
    } else { console.error("[vision-proxy] vp analyze failed or timed out"); }
    return null;
  }
  if (result.status !== 0 || !result.stdout.trim()) {
    console.error(\`[vision-proxy] vp analyze exited with status \${result.status ?? "?"}\`);
    return null;
  }
  return result.stdout.trimEnd();
}

function withImageInstruction(description: string): string {
  return (
    "Do not use the Read tool on image files. " +
    "vision-proxy has already routed the image(s) through a vision-input model " +
    "and produced the description below. " +
    "Treat that description as the image content. " +
    "If you need a more specific or detailed analysis, ask in the prompt instead of reading the file.\\n\\n" +
    description
  );
}

const messageHook: Hooks["chat.message"] = async (input, output) => {
  const prompt = output.message.content;
  if (typeof prompt !== "string") return;
  const images = extractImagePaths(prompt);
  const sessionId = input.sessionID;
  const refImages = resolveImageRefs(prompt, sessionId);
  const allImages = [...images, ...refImages];
  if (allImages.length === 0) return;
  const description = runAnalyze(allImages, prompt);
  if (!description) return;
  output.additionalContext = withImageInstruction(description);
};

function readToolFilePath(toolName: string, toolInput: Record<string, unknown>, cwd?: string): string | null {
  if (toolName !== "Read") return null;
  const file = (toolInput.file_path ?? toolInput.path) as string | undefined;
  if (!isImagePath(file)) return null;
  return resolveImagePath(file, cwd);
}

const toolExecuteBeforeHook: Hooks["tool.execute.before"] = async (input, output) => {
  const tool = input.tool;
  // Find cwd from session or use process.cwd()
  const cwd = process.cwd();
  const file = readToolFilePath(tool, output.args as Record<string, unknown>, cwd);
  if (!file) return;
  const description = runAnalyze([file]);
  if (!description) return;
  // Set additionalContext on the tool call output
  output.additionalContext = withImageInstruction(description);
  // Deny the Read tool by throwing - opencode will show the additionalContext
  throw new Error("Image read intercepted by vision-proxy. Description injected as context.");
};

export default function setup(): Hooks {
  return {
    "chat.message": messageHook,
    "tool.execute.before": toolExecuteBeforeHook,
  };
}
`;
