/**
 * Embedded opencode v1 plugin source.
 *
 * `vp integration install opencode` writes this exact TypeScript into
 * `~/.config/opencode/plugins/vision-proxy.ts`. opencode auto-loads local
 * plugins from that directory, so it must run as plain TypeScript with no
 * build step.
 *
 * The plugin registers hooks for parity with claude-code/codex:
 * - `chat.message`: extracts image paths from the user text, decodes attached
 *   image parts (data URLs), runs `vp analyze`, removes the analyzed image
 *   parts from the message, and injects the fenced description as a synthetic
 *   text part (like UserPromptSubmit).
 * - `tool.execute.before`: intercepts `read` tool calls on image files, runs
 *   `vp analyze`, and denies the read by throwing an error whose message
 *   carries the description (like PreToolUse Read).
 *
 * No new `analyze_image` tool is registered - the agent uses its native Read
 * tool, which the hook intercepts.
 *
 * Fail-open: if `vp` is missing or exits non-zero, the hook logs and leaves
 * the original message or tool call unchanged.
 *
 * NOTE: this module exports the plugin source as a raw string. It uses
 * String.raw so regexes inside the generated source are written exactly once.
 * The generated source must therefore never contain a backtick or a dollar
 * sign followed by an opening brace.
 */
export const OPENCODE_PLUGIN_SOURCE = String.raw`/**
 * vision-proxy opencode plugin.
 *
 * Auto-generated by vp integration install opencode. Do not edit by hand;
 * re-run the installer to regenerate after a vision-proxy upgrade.
 *
 * Registers hooks for parity with claude-code/codex:
 * - chat.message -> like UserPromptSubmit
 * - tool.execute.before (read) -> like PreToolUse Read
 *
 * No new analyze_image tool - the agent uses native Read which hook intercepts.
 *
 * The description text returned by vp is attacker-controlled (it comes from
 * an external vision model), so it is forwarded verbatim inside its UNTRUSTED
 * fence and the consumer must treat it as untrusted input.
 */
import type { Hooks } from "@opencode-ai/plugin";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

// __VP_VERSION__PLACEHOLDER__

const IMAGE_EXT = ["jpg", "jpeg", "png", "gif", "webp", "bmp", "tiff", "tif", "ico", "avif"];
const MAX_BUFFER_BYTES = 10 * 1024 * 1024;
const TIMEOUT_MS = Number(process.env.VP_HOOK_TIMEOUT_MS ?? 30000);

function vpEntryToSpawn(cmd: string): { command: string; args: string[] } {
  if (/\.js$/i.test(cmd)) return { command: process.execPath, args: [cmd] };
  return { command: cmd, args: [] };
}

function resolveVpBin(): string {
  const env = process.env.VP_BIN;
  if (env?.trim()) return env;
  return "vp";
}

function isImagePath(p: unknown): boolean {
  if (!p || typeof p !== "string") return false;
  const ext = p.split(".").pop()?.toLowerCase();
  return !!ext && IMAGE_EXT.includes(ext);
}

function resolveImagePath(p: string | undefined | null, cwd?: string): string | null {
  if (!p) return null;
  if (p.startsWith("/") || p.startsWith("~") || /^[a-zA-Z]:[/\\]/.test(p)) return p;
  if (cwd && (p.startsWith("./") || p.startsWith("../"))) {
    try { return resolve(cwd, p); } catch { return p; }
  }
  return p;
}

/**
 * Extract candidate image paths from free text.
 *
 * Two passes, both anchored to a delimiter (start-of-text or whitespace/quote/
 * bracket) so words like "nota/path.jpeg" do not match:
 * 1. Absolute-ish paths: drive letter, "/" or "~" prefix, ending in a known
 *    image extension.
 * 2. Relative paths starting with "./" or "../".
 */
function extractImagePaths(text: string): string[] {
  const found: string[] = [];
  const seen = new Set<string>();
  const add = (raw: string | undefined) => {
    // Trim trailing punctuation that commonly follows a path in prose.
    const t = (raw ?? "").trim().replace(/[.,;:!?)\]}>'"]+$/, "");
    if (!t || t.includes("//")) return;
    if (seen.has(t)) return;
    seen.add(t);
    found.push(t);
  };
  const D = "[\\s'\"()]";
  const B = "[^\\s'\"()*?|]";
  const EXT = "(?:" + IMAGE_EXT.join("|") + ")";
  const reAbs = new RegExp(
    "(^|" + D + ")((?:[a-zA-Z]:[/\\\\]|[/~])" + B + "*\\." + EXT + ")\\b",
    "gi",
  );
  for (const m of text.matchAll(reAbs)) add(m[2]);
  const reRel = new RegExp(
    "(^|" + D + ")((?:\\.\\.?/)" + B + "*\\." + EXT + ")\\b",
    "gi",
  );
  for (const m of text.matchAll(reRel)) add(m[2]);
  return found;
}

/** Run vp analyze and return the fenced description, or null on failure. */
function runAnalyze(images: string[]): string | null {
  if (images.length === 0) return null;
  const vp = resolveVpBin();
  const { command, args: prefix } = vpEntryToSpawn(vp);
  const maxTokens = Number(process.env.VP_MAX_OUTPUT_TOKENS ?? 2000);
  const args = [...prefix, "analyze", ...images, "--max-output-tokens", String(maxTokens)];
  const result = spawnSync(command, args, { encoding: "utf8", timeout: TIMEOUT_MS, maxBuffer: MAX_BUFFER_BYTES });
  if (result.error) {
    if ((result.error as NodeJS.ErrnoException).code === "ENOENT") {
      console.error("[vision-proxy] vp binary not found: " + vp);
    } else { console.error("[vision-proxy] vp analyze failed or timed out"); }
    return null;
  }
  if (result.status !== 0 || !result.stdout.trim()) {
    console.error("[vision-proxy] vp analyze exited with status " + (result.status ?? "?"));
    return null;
  }
  return result.stdout.trimEnd();
}

function withImageInstruction(description: string): string {
  return (
    "Do not use the Read tool on image files. " +
    "vision-proxy has already routed the image(s) through a vision-input model " +
    "and produced the description below. " +
    "Treat that description as the image content. " +
    "If you need a more specific or detailed analysis, ask in the prompt instead of reading the file.\n\n" +
    description
  );
}

/** Decode a data URL into a temp image file; returns null when unsupported. */
function writeDataUrlToTemp(url: string): string | null {
  const m = /^data:image\/([a-z0-9.+-]+);base64,(.*)$/i.exec(url);
  if (!m) return null;
  const subtype = m[1].toLowerCase();
  const ext = IMAGE_EXT.includes(subtype) ? subtype : null;
  if (!ext) return null;
  let dir: string;
  try {
    dir = mkdtempSync(join(tmpdir(), "vp-opencode-"));
  } catch {
    return null;
  }
  try {
    const path = join(dir, "image." + ext);
    writeFileSync(path, Buffer.from(m[2], "base64"));
    return path;
  } catch {
    try { rmSync(dir, { recursive: true, force: true }); } catch { /* best effort */ }
    return null;
  }
}

function cleanupTempDirs(paths: string[]): void {
  const dirs = new Set(paths.map((p) => resolve(p, "..")));
  for (const d of dirs) {
    if (d === tmpdir()) continue;
    try { rmSync(d, { recursive: true, force: true }); } catch { /* best effort */ }
  }
}

/** Monotonic part id generator; opencode requires ids to start with "prt". */
let partCounter = 0;
function newPartId(): string {
  partCounter += 1;
  return "prt-vp-" + Date.now().toString(36) + "-" + partCounter + "-" + Math.random().toString(36).slice(2, 8);
}

async function handleChatMessage(
  input: { sessionID: string; messageID?: string },
  output: { message: { sessionID?: string }; parts: any[] },
  cwd: string,
): Promise<void> {
  // Collect the user-visible text and attached image parts.
  const textChunks: string[] = [];
  const attached: Array<{ index: number; part: any }> = [];
  output.parts.forEach((part: any, index: number) => {
    if (part?.type === "text" && typeof part.text === "string") {
      textChunks.push(part.text);
    } else if (
      part?.type === "file" &&
      typeof part.mime === "string" &&
      part.mime.startsWith("image/") &&
      typeof part.url === "string" &&
      part.url.startsWith("data:")
    ) {
      attached.push({ index, part });
    }
  });
  const promptText = textChunks.join("\n");
  const tempFiles: string[] = [];
  const images: string[] = [];
  // URLs of attached parts that were successfully decoded for analysis.
  const analyzedUrls: string[] = [];
  try {
    for (const item of attached) {
      const tempPath = writeDataUrlToTemp(item.part.url);
      if (tempPath) {
        tempFiles.push(tempPath);
        images.push(tempPath);
        analyzedUrls.push(item.part.url);
      }
    }
    for (const candidate of extractImagePaths(promptText)) {
      const resolvedPath = resolveImagePath(candidate, cwd);
      if (resolvedPath && isImagePath(resolvedPath) && existsSync(resolvedPath)) images.push(resolvedPath);
    }
    const uniqueImages = [...new Set(images)];
    if (uniqueImages.length === 0) return;
    const description = runAnalyze(uniqueImages);
    if (!description) return;
    // Remove only the described image parts (undecodable attachments stay for
    // native handling) so no analyzed image bytes reach the model, then append
    // the description as a synthetic context part.
    const describedUrls = new Set(analyzedUrls);
    for (let i = output.parts.length - 1; i >= 0; i--) {
      const part: any = output.parts[i];
      if (part?.type === "file" && describedUrls.has(part.url)) output.parts.splice(i, 1);
    }
    const anchor: any = output.parts[output.parts.length - 1];
    output.parts.push({
      id: newPartId(),
      sessionID: anchor?.sessionID ?? output.message?.sessionID ?? input.sessionID,
      messageID: anchor?.messageID ?? output.message?.id ?? input.messageID,
      type: "text",
      synthetic: true,
      text: withImageInstruction(description),
    });
  } finally {
    cleanupTempDirs(tempFiles);
  }
}

async function handleToolExecuteBefore(
  input: { tool: string },
  output: { args: any },
  cwd: string,
): Promise<void> {
  if (input.tool !== "read") return;
  const argPath =
    output.args && typeof output.args.filePath === "string"
      ? output.args.filePath
      : undefined;
  if (!isImagePath(argPath)) return;
  const filePath = resolveImagePath(argPath, cwd);
  if (!filePath || !existsSync(filePath)) return;
  const description = runAnalyze([filePath]);
  // Fail-open: when analysis is unavailable, allow the original read.
  if (!description) return;
  // Denying by throw surfaces this message to the model as the tool result,
  // which carries both the instruction and the description.
  throw new Error(withImageInstruction(description));
}

export default async function visionProxyPlugin(input: {
  directory?: string;
}): Promise<Hooks> {
  const pluginCwd = typeof input?.directory === "string" && input.directory ? input.directory : process.cwd();
  return {
    "chat.message": async (innerInput, innerOutput) => {
      await handleChatMessage(innerInput as any, innerOutput as any, pluginCwd);
    },
    "tool.execute.before": async (innerInput, innerOutput) => {
      await handleToolExecuteBefore(innerInput as any, innerOutput as any, pluginCwd);
    },
  };
}
`;
