/**
 * Embedded Pi extension source.
 *
 * `vp integration install pi` writes this exact TypeScript into Pi's global
 * extensions directory (`~/.pi/agent/extensions/vision-proxy.ts`). Pi auto-loads
 * it via its `jiti` loader, so it must run as plain TypeScript with no build step.
 *
 * The extension hooks into Pi's lifecycle events to automatically describe images
 * at parity with the Claude Code / Codex `vp hook` integration:
 *   - `input`: extracts images attached to the submission (base64 content) plus
 *     image paths referenced in the text, runs `vp analyze`, strips the image
 *     bytes and path mentions from the submission, and stashes the description.
 *     Attachments whose mime type is outside the supported set are forwarded
 *     unchanged to the model instead of being dropped. When the submission is
 *     queued for streaming delivery (event.streamingBehavior set), the fenced
 *     description is embedded in the transformed text instead of the system
 *     prompt, because before_agent_start does not fire for queued messages.
 *   - `before_agent_start`: appends the stashed fenced UNTRUSTED description to
 *     the system prompt (the only cross-turn injection channel Pi consumes).
 *   - `tool_result`: intercepts `read` tool results on image files and replaces
 *     the tool result content with the fenced description so no image bytes
 *     reach the model.
 *
 * Pi fires the `input` event for every `session.prompt()` submission, including
 * ones that arrive while the agent is streaming and are queued via the
 * `streamingBehavior` option. The event is NOT fired for messages dispatched
 * through the separate `session.steer()` / `session.followUp()` APIs (e.g. the
 * RPC `steer` / `follow_up` commands or queued-message retry paths); those
 * submissions are forwarded to the model with their attachments intact.
 *
 * No tool is registered, keeping system tokens low.
 *
 * Fail-open: if `vp` is missing, exits non-zero, or any other error occurs, the
 * extension returns undefined and Pi proceeds unchanged. Image-derived text is
 * attacker-controlled, so the analyzer fence stays on.
 *
 * NOTE: this module exports the extension source as a raw string. It uses
 * String.raw so regexes inside the generated source are written exactly once.
 * The generated source must therefore never contain a backtick or a dollar
 * sign followed by an opening brace.
 */
export const PI_EXTENSION_SOURCE = String.raw`/**
 * vision-proxy Pi extension.
 *
 * Auto-generated by vp integration install pi. Do not edit by hand; re-run
 * the installer to regenerate after a vision-proxy upgrade.
 *
 * Hooks into Pi lifecycle events to automatically describe images at parity
 * with the Claude Code / Codex vp hook integration. No tool is registered.
 *
 * Supported image attachments are analyzed and stripped from the submission;
 * attachments with an unsupported mime type are forwarded to the model
 * unchanged. The 'input' event is fired for every session.prompt() submission,
 * including streaming ones queued via the streamingBehavior option, but NOT
 * for messages dispatched through session.steer() or session.followUp()
 * directly (e.g. RPC steer / follow_up commands).
 *
 * The description text returned by vp is attacker-controlled (it comes from
 * an external vision model), so it is forwarded verbatim inside its UNTRUSTED
 * fence and the consumer must treat it as untrusted input.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";

// __VP_VERSION__PLACEHOLDER__

const MAX_BUFFER_BYTES = 10 * 1024 * 1024;
const TIMEOUT_MS = Number(process.env.VP_HOOK_TIMEOUT_MS ?? 30000);

// Known image file extensions (lowercased, no dot).
const IMAGE_EXT = ["jpg", "jpeg", "png", "gif", "webp", "bmp", "tiff", "tif", "ico", "avif"];

/** Check if a path ends in a known image extension. */
function isImagePath(p: unknown): boolean {
  if (!p || typeof p !== "string") return false;
  const ext = p.split(".").pop()?.toLowerCase();
  return !!ext && IMAGE_EXT.includes(ext);
}

/** Resolve a path that may be relative against cwd. */
function resolveImagePath(p: string | undefined | null, cwd?: string): string | null {
  if (!p) return null;
  if (p.startsWith("/") || p.startsWith("~") || /^[a-zA-Z]:[/\\]/.test(p)) {
    return p;
  }
  if (cwd && (p.startsWith("./") || p.startsWith("../"))) {
    try {
      return resolve(cwd, p);
    } catch {
      return p;
    }
  }
  return p;
}

/**
 * Extract candidate image paths from free text.
 *
 * Two passes, both anchored to a delimiter (start-of-text or whitespace/quote/
 * bracket) so words like "nota/path.jpeg" do not match:
 * 1. Absolute-ish paths: drive letter, "/" or "~" prefix, ending in a known
 *    image extension.
 * 2. Relative paths starting with "./" or "../".
 */
function extractImagePaths(text: string): string[] {
  const found: string[] = [];
  const seen = new Set<string>();
  const add = (raw: string | undefined) => {
    // Trim trailing punctuation that commonly follows a path in prose.
    const t = (raw ?? "").trim().replace(/[.,;:!?)\]}>'"]+$/, "");
    if (!t || t.includes("//")) return;
    if (seen.has(t)) return;
    seen.add(t);
    found.push(t);
  };
  const D = "[\\s'\"()]";
  const B = "[^\\s'\"()*?|]";
  const EXT = "(?:" + IMAGE_EXT.join("|") + ")";
  const reAbs = new RegExp(
    "(^|" + D + ")((?:[a-zA-Z]:[/\\\\]|[/~])" + B + "*\\." + EXT + ")\\b",
    "gi",
  );
  for (const m of text.matchAll(reAbs)) add(m[2]);
  const reRel = new RegExp(
    "(^|" + D + ")((?:\\.\\.?/)" + B + "*\\." + EXT + ")\\b",
    "gi",
  );
  for (const m of text.matchAll(reRel)) add(m[2]);
  return found;
}

/** Escape every regex special character in a literal path fragment. */
function escapeRegExp(s: string): string {
  const bs = "\\";
  // Backslash must be escaped first so later insertions are not re-escaped.
  let out = s.split(bs).join(bs + bs);
  for (const ch of [".", "*", "+", "?", "^", "$", "{", "}", "(", ")", "[", "]", "|"]) {
    out = out.split(ch).join(bs + ch);
  }
  return out;
}

/** Strip the given literal path strings out of the prompt text. */
function stripImagePaths(text: string, paths: string[]): string {
  if (paths.length === 0) return text;
  // Longest first so overlapping candidates remove completely.
  const sorted = [...paths].sort((a, b) => b.length - a.length);
  let result = text;
  for (const p of sorted) {
    result = result.replace(new RegExp(escapeRegExp(p), "g"), "");
  }
  return result;
}

/** Resolve the vp binary into a spawn command, supporting .js entry points. */
function vpEntryToSpawn(cmd: string): { command: string; args: string[] } {
  if (/\.js$/i.test(cmd)) return { command: process.execPath, args: [cmd] };
  return { command: cmd, args: [] };
}

function resolveVpBin(): string {
  const env = process.env.VP_BIN;
  if (env?.trim()) return env;
  return "vp";
}

/** Run vp analyze and return the fenced description, or null on failure. */
function runAnalyze(images: string[]): string | null {
  if (images.length === 0) return null;
  const vp = resolveVpBin();
  const { command, args: prefix } = vpEntryToSpawn(vp);
  const maxTokens = Number(process.env.VP_MAX_OUTPUT_TOKENS ?? 2000);
  const args = [...prefix, "analyze", ...images, "--max-output-tokens", String(maxTokens)];
  const result = spawnSync(command, args, {
    encoding: "utf8",
    timeout: TIMEOUT_MS,
    maxBuffer: MAX_BUFFER_BYTES,
  });
  if (result.error) {
    if ((result.error as NodeJS.ErrnoException).code === "ENOENT") {
      process.stderr.write("[vision-proxy] vp binary not found: " + vp + "\n");
    } else {
      process.stderr.write("[vision-proxy] vp analyze failed or timed out\n");
    }
    return null;
  }
  if (result.status !== 0 || !result.stdout.trim()) {
    process.stderr.write("[vision-proxy] vp analyze exited with status " + (result.status ?? "?") + "\n");
    return null;
  }
  return result.stdout.trimEnd();
}

/** Read mode from vp config get --json or VP_MODE. Returns "always" | "off". */
function getMode(): "always" | "off" {
  try {
    const vp = resolveVpBin();
    const { command, args: prefix } = vpEntryToSpawn(vp);
    const result = spawnSync(command, [...prefix, "config", "get", "--json"], {
      encoding: "utf8",
      timeout: 5000,
      maxBuffer: 1024 * 1024,
    });
    if (!result.error && result.status === 0 && result.stdout.trim()) {
      const cfg = JSON.parse(result.stdout);
      const mode = cfg.mode as string | undefined;
      if (mode === "always" || mode === "off") return mode;
    }
  } catch {
    // fall through to env resolution
  }
  const envMode = process.env.VP_MODE;
  if (envMode === "always" || envMode === "off") return envMode;
  return "always";
}

/**
 * Write base64 image data into a fresh temp dir and return the file path.
 * The caller owns the returned directory and must clean it up.
 */
function writeTempImage(base64: string, mimeType: string): string | null {
  const subtype = (mimeType.split("/")[1] ?? "").toLowerCase();
  const ext = IMAGE_EXT.includes(subtype) ? subtype : null;
  if (!ext) return null;
  let dir: string;
  try {
    dir = mkdtempSync(join(tmpdir(), "vp-pi-"));
  } catch {
    return null;
  }
  try {
    const path = join(dir, "image." + ext);
    writeFileSync(path, Buffer.from(base64, "base64"));
    return path;
  } catch {
    try { rmSync(dir, { recursive: true, force: true }); } catch { /* best effort */ }
    return null;
  }
}

/** Remove the temp dirs that owned the given temp files. */
function cleanupTempDirs(paths: string[]): void {
  const dirs = new Set(paths.map((p) => resolve(p, "..")));
  for (const d of dirs) {
    if (d === tmpdir()) continue;
    try { rmSync(d, { recursive: true, force: true }); } catch { /* best effort */ }
  }
}

function withImageInstruction(description: string): string {
  return (
    "Do not use the Read tool on image files. " +
    "vision-proxy has already routed the image(s) through a vision-input model " +
    "and produced the description below. " +
    "Treat that description as the image content. " +
    "If you need a more specific or detailed analysis, ask in the prompt instead of reading the file.\n\n" +
    description
  );
}

// Description produced by the most recent analyzed submission. For idle
// prompts, Pi fires the input event before before_agent_start so this handoff
// is sequential per prompt. For prompts queued while the agent is streaming
// (event.streamingBehavior set), before_agent_start is never emitted, so the
// description is embedded in the transformed text and pendingDescription is
// left untouched to avoid leaking the description into a later idle prompt.
let pendingDescription: string | null = null;

export default function setup(pi: ExtensionAPI): void {
  // --- input: strip image bytes/paths from the submission ---
  pi.on("input", async (event) => {
    if (getMode() === "off") return undefined;
    const tempFiles: string[] = [];
    const images: string[] = [];
    // Attachments we cannot analyze (unsupported mime type) are passed through
    // unchanged instead of being silently dropped.
    const passthroughImages: unknown[] = [];
    let text = typeof event.text === "string" ? event.text : "";
    try {
      // Attached images arrive as base64 content without a path.
      if (Array.isArray(event.images)) {
        for (const img of event.images as Array<{ data?: unknown; mimeType?: unknown }>) {
          if (!img || typeof img.data !== "string" || typeof img.mimeType !== "string") continue;
          const tempPath = writeTempImage(img.data, img.mimeType);
          if (tempPath) {
            tempFiles.push(tempPath);
            images.push(tempPath);
          } else {
            passthroughImages.push(img);
          }
        }
      }
      // Image paths referenced in the text itself.
      const referenced = extractImagePaths(text)
        .map((p) => resolveImagePath(p))
        .filter((p): p is string => !!p && isImagePath(p) && existsSync(p));
      images.push(...referenced);
      const uniqueImages = [...new Set(images)];
      if (uniqueImages.length === 0) return undefined;

      const description = runAnalyze(uniqueImages);
      if (!description) return undefined; // fail-open

      let stripped = stripImagePaths(text, referenced);
      if (!stripped.trim() && passthroughImages.length === 0) {
        stripped = "(images were attached; see the vision-proxy description below)";
      }
      // Queued streaming prompts never fire before_agent_start, so embedding
      // the description in the text is the only channel that reaches the model
      // for that turn. Stash instead for the idle path so before_agent_start
      // can append it to the system prompt.
      if (event.streamingBehavior) {
        return {
          action: "transform",
          text: stripped + "\n\n" + withImageInstruction(description),
          images: passthroughImages as Array<{ type: "image"; data: string; mimeType: string }>,
        };
      }
      pendingDescription = description;
      return {
        action: "transform",
        text: stripped,
        images: passthroughImages as Array<{ type: "image"; data: string; mimeType: string }>,
      };
    } finally {
      cleanupTempDirs(tempFiles);
    }
  });

  // --- before_agent_start: inject the stashed description into the system prompt ---
  pi.on("before_agent_start", async (event) => {
    if (!pendingDescription) return undefined;
    const description = pendingDescription;
    pendingDescription = null;
    return { systemPrompt: (event.systemPrompt ?? "") + "\n\n" + description };
  });

  // --- tool_result: replace read results on image files ---
  pi.on("tool_result", async (event) => {
    if (event.toolName !== "read") return undefined;
    const argPath = event.input && typeof event.input.path === "string" ? event.input.path : undefined;
    if (!isImagePath(argPath)) return undefined;
    if (getMode() === "off") return undefined;
    const filePath = resolveImagePath(argPath);
    if (!filePath || !existsSync(filePath)) return undefined;
    const description = runAnalyze([filePath]);
    if (!description) return undefined; // fail-open
    return { content: [{ type: "text", text: withImageInstruction(description) }] };
  });
}
`;
