/**
 * Embedded Pi extension source.
 *
 * `vp integration install pi` writes this exact TypeScript into Pi's global
 * extensions directory (`~/.pi/agent/extensions/vision-proxy.ts`). Pi auto-loads
 * it via its `jiti` loader, so it must run as plain TypeScript with no build step.
 *
 * The extension registers a single `analyze_image` tool that delegates to the
 * standalone `vp` CLI. It is intentionally Pi-free at runtime: the only coupling
 * to Pi is the extension entry point and the tool-registration API.
 *
 * Fail-open: if `vp` is missing or exits non-zero, the tool returns a clear
 * error string rather than throwing, so the agent can proceed unchanged.
 */
export const PI_EXTENSION_SOURCE = `/**
 * vision-proxy Pi extension.
 *
 * Auto-generated by \`vp integration install pi\`. Do not edit by hand; re-run
 * the installer to regenerate after a vision-proxy upgrade.
 *
 * Registers an \`analyze_image\` tool backed by the standalone \`vp\` CLI. The
 * description text returned by \`vp\` is attacker-controlled (it comes from an
 * external vision model), so it is forwarded verbatim and the consumer must
 * treat it as untrusted input.
 */
import { tool, type Agent } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { spawnSync } from "node:child_process";

const MAX_BUFFER_BYTES = 10 * 1024 * 1024;
const TIMEOUT_MS = Number(process.env.VP_HOOK_TIMEOUT_MS ?? 30000);

export default async function setup(agent: Agent): Promise<void> {
  agent.tool({
    name: "analyze_image",
    description:
      "Describe one or more images using the vision-proxy CLI. Returns a fenced, UNTRUSTED " +
      "description for each image. Use this to extract information from screenshots, diagrams, " +
      "or photos the user references by path.",
    schema: Type.Object({
      paths: Type.Array(Type.String(), {
        description: "Absolute or project-relative paths to image files.",
      }),
      question: Type.Optional(
        Type.String({ description: "Optional question to analyze the image against." }),
      ),
      format: Type.Optional(
        Type.String({ description: "Optional grounding format override (e.g. qwen_pixels)." }),
      ),
    }),
    async run({ paths, question, format }: { paths: string[]; question?: string; format?: string }) {
      if (!paths || paths.length === 0) {
        return { error: "analyze_image requires at least one image path." };
      }
      const vp = process.env.VP_BIN || "vp";
      const args = ["analyze", "--json", ...paths];
      if (question) args.push("--question", question);
      if (format) args.push("--format", format);
      const result = spawnSync(vp, args, {
        encoding: "utf8",
        timeout: TIMEOUT_MS,
        maxBuffer: MAX_BUFFER_BYTES,
      });
      if (result.error) {
        const reason =
          result.error.code === "ENOENT"
            ? \`vp binary not found: \${vp} (set VP_BIN or add vp to PATH)\`
            : "vp analyze failed or timed out";
        return { error: reason };
      }
      if (result.status !== 0) {
        return { error: \`vp analyze exited with status \${result.status ?? "?"}: \${result.stderr.trim()}\` };
      }
      try {
        const parsed = JSON.parse(result.stdout);
        return {
          cacheHit: parsed.cacheHit,
          records: parsed.records,
        };
      } catch {
        return { error: "vp analyze returned output that was not valid JSON." };
      }
    },
  });
}
`;
