/**
 * Embedded Pi extension source.
 *
 * `vp integration install pi` writes this exact TypeScript into Pi's global
 * extensions directory (`~/.pi/agent/extensions/vision-proxy.ts`). Pi auto-loads
 * it via its `jiti` loader, so it must run as plain TypeScript with no build step.
 *
 * The extension hooks into Pi's lifecycle events to automatically describe images
 * at parity with the Claude Code / Codex `vp hook` integration:
 *   - `input`: a no-op that returns immediately so the user's prompt is accepted
 *     and submitted the instant they press Enter. It never awaits `vp analyze`,
 *     so prompt submission is never blocked on the vision call.
 *   - `context`: the single analysis point. It fires right before Pi sends the
 *     turn's messages to the model. For each user message it finds image
 *     attachments (base64 content) and image paths referenced in the text, runs
 *     `vp analyze` (with a live "[vision-proxy] Analyzing..." notification), and
 *     replaces the image content with the fenced UNTRUSTED description. Because
 *     this runs after the prompt has already been submitted and rendered, the
 *     user sees their prompt immediately and the wait never blocks submission.
 *     The referenced image path (if any) stays in the user prompt for parity with
 *     Claude Code / Codex, which also cannot rewrite the submission.
 *   - `tool_result`: intercepts `read` tool results on image files and replaces
 *     the tool result content with the fenced description so no image bytes
 *     reach the model.
 *
 * Pi fires the `input` event for every `session.prompt()` submission, including
 * ones that arrive while the agent is streaming and are queued via the
 * `streamingBehavior` option. Queued streaming prompts are forwarded through to
 * the `context` handler (which analyzes them just like any other message), so
 * there is a single analysis path and no prompt submit is ever blocked.
 *
 * No tool is registered, keeping system tokens low.
 *
 * Fail-open: if `vp` is missing, exits non-zero, or any other error occurs, the
 * extension returns undefined and Pi proceeds unchanged. Image-derived text is
 * attacker-controlled, so the analyzer fence stays on.
 *
 * NOTE: this module exports the extension source as a raw string. It uses
 * String.raw so regexes inside the generated source are written exactly once.
 * The generated source must therefore never contain a backtick or a dollar
 * sign followed by an opening brace.
 */
export const PI_EXTENSION_SOURCE = String.raw`/**
 * vision-proxy Pi extension.
 *
 * Auto-generated by vp integration install pi. Do not edit by hand; re-run
 * the installer to regenerate after a vision-proxy upgrade.
 *
 * Hooks into Pi lifecycle events to automatically describe images at parity
 * with the Claude Code / Codex vp hook integration. No tool is registered.
 *
 * The analysis runs in the context event, which fires right before the turn's
 * messages are sent to the model. This keeps the prompt submit instant: the
 * user's text is accepted the moment they press Enter, and the (slower) vision
 * call happens at send-time without ever blocking submission. The input event
 * is therefore a no-op.
 *
 * The description text returned by vp is attacker-controlled (it comes from
 * an external vision model), so it is forwarded verbatim inside its UNTRUSTED
 * fence and the consumer must treat it as untrusted input.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawn, spawnSync } from "node:child_process";
import { existsSync, writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir, homedir } from "node:os";

// __VP_VERSION__PLACEHOLDER__

const TIMEOUT_MS = Number(process.env.VP_HOOK_TIMEOUT_MS ?? 30000);

// Known image file extensions (lowercased, no dot).
const IMAGE_EXT = ["jpg", "jpeg", "png", "gif", "webp", "bmp", "tiff", "tif", "ico", "avif"];

/** Check if a path ends in a known image extension. */
function isImagePath(p: unknown): boolean {
  if (!p || typeof p !== "string") return false;
  const ext = p.split(".").pop()?.toLowerCase();
  return !!ext && IMAGE_EXT.includes(ext);
}

/** Resolve a path that may be relative against cwd. */
function resolveImagePath(p: string | undefined | null, cwd?: string): string | null {
  if (!p) return null;
  // Expand a leading "~" to the user's home directory. Node's fs APIs do not
  // expand tildes, so an unexpanded "~/..." path would fail the existsSync
  // guard below and be silently dropped instead of analyzed.
  if (p === "~" || p.startsWith("~/")) {
    const home = homedir();
    if (home) return p === "~" ? home : join(home, p.slice(2));
  }
  if (p.startsWith("/") || p.startsWith("~") || /^[a-zA-Z]:[/\\]/.test(p)) {
    return p;
  }
  if (cwd && (p.startsWith("./") || p.startsWith("../"))) {
    try {
      return resolve(cwd, p);
    } catch {
      return p;
    }
  }
  return p;
}

/**
 * Extract candidate image paths from free text.
 *
 * Two passes, both anchored to a delimiter (start-of-text or whitespace/quote/
 * bracket) so words like "nota/path.jpeg" do not match:
 * 1. Absolute-ish paths: drive letter, "/" or "~" prefix, ending in a known
 *    image extension.
 * 2. Relative paths starting with "./" or "../".
 */
function extractImagePaths(text: string): string[] {
  const found: string[] = [];
  const seen = new Set<string>();
  const add = (raw: string | undefined) => {
    // Trim trailing punctuation that commonly follows a path in prose.
    const t = (raw ?? "").trim().replace(/[.,;:!?)\]}>'"]+$/, "");
    if (!t || t.includes("//")) return;
    if (seen.has(t)) return;
    seen.add(t);
    found.push(t);
  };
  const D = "[\\s'\"()]";
  const B = "[^\\s'\"()*?|]";
  const EXT = "(?:" + IMAGE_EXT.join("|") + ")";
  const reAbs = new RegExp(
    "(^|" + D + ")((?:[a-zA-Z]:[/\\\\]|[/~])" + B + "*\\." + EXT + ")\\b",
    "gi",
  );
  for (const m of text.matchAll(reAbs)) add(m[2]);
  const reRel = new RegExp(
    "(^|" + D + ")((?:\\.\\.?/)" + B + "*\\." + EXT + ")\\b",
    "gi",
  );
  for (const m of text.matchAll(reRel)) add(m[2]);
  return found;
}

/** De-duplicate by stable id, preserving first-seen order. */
function dedupe<T extends { id: string }>(items: T[]): T[] {
  const seen = new Set<string>();
  const out: T[] = [];
  for (const it of items) {
    if (seen.has(it.id)) continue;
    seen.add(it.id);
    out.push(it);
  }
  return out;
}

/** Resolve the vp binary into a spawn command, supporting .js entry points. */
function vpEntryToSpawn(cmd: string): { command: string; args: string[] } {
  if (/\.js$/i.test(cmd)) return { command: process.execPath, args: [cmd] };
  return { command: cmd, args: [] };
}

/** Resolve the vp binary path, honoring the VP_BIN override and defaulting to "vp". */
function resolveVpBin(): string {
  const env = process.env.VP_BIN;
  if (env?.trim()) return env;
  return "vp";
}

/** Run vp analyze (async) and return the fenced description, or null on failure. */
async function runAnalyze(images: string[], signal?: unknown, question?: string): Promise<string | null> {
  return new Promise((resolve) => {
    if (!images || images.length === 0) return resolve(null);
    const vp = resolveVpBin();
    const { command, args: prefix } = vpEntryToSpawn(vp);
    const maxTokens = Number(process.env.VP_MAX_OUTPUT_TOKENS ?? 2000);
    const args = [...prefix, "analyze", ...images, "--max-output-tokens", String(maxTokens)];
    if (question && question.trim()) args.push("--question", question.trim());
    let settled = false;
    let timer: unknown = null;
    const finish = (val: string | null) => {
      if (settled) return;
      settled = true;
      if (timer) clearTimeout(timer as NodeJS.Timeout);
      resolve(val);
    };
    let child;
    try {
      child = spawn(command, args);
    } catch (err) {
      const msg = err && (err as Error).message ? (err as Error).message : String(err);
      process.stderr.write("[vision-proxy] failed to spawn vp: " + msg + "\n");
      return resolve(null);
    }
    let stdout = "";
    child.stdout.on("data", (d) => { stdout += String(d); });
    child.stderr.on("data", (d) => { process.stderr.write(String(d)); });
    child.on("error", (err) => {
      const e = err as NodeJS.ErrnoException;
      if (e && e.code === "ENOENT") process.stderr.write("[vision-proxy] vp binary not found: " + vp + "\n");
      else process.stderr.write("[vision-proxy] vp analyze failed: " + (e && e.message ? e.message : String(err)) + "\n");
      finish(null);
    });
    child.on("close", (code) => {
      const out = stdout.trim();
      if (code !== 0 || !out) {
        process.stderr.write("[vision-proxy] vp analyze exited with status " + (code == null ? "?" : String(code)) + "\n");
        finish(null);
      } else {
        finish(out.trimEnd());
      }
    });
    timer = setTimeout(() => {
      try { if (child) child.kill("SIGKILL"); } catch { /* ignore */ }
      process.stderr.write("[vision-proxy] vp analyze timed out\n");
      finish(null);
    }, TIMEOUT_MS);
    if (signal && (signal as AbortSignal).addEventListener) {
      const onAbort = () => {
        // Settle immediately so the context handler does not hang until the hard
        // timeout waiting on a child that swallows SIGTERM and never emits "close".
        finish(null);
        try { if (child) child.kill("SIGTERM"); } catch { /* ignore */ }
        // Force-stop a child that handles SIGTERM and never exits.
        try {
          const dying = child;
          setTimeout(() => { try { if (dying) dying.kill("SIGKILL"); } catch { /* ignore */ } }, 1000);
        } catch { /* ignore */ }
      };
      if ((signal as AbortSignal).aborted) onAbort();
      else (signal as AbortSignal).addEventListener("abort", onAbort, { once: true });
    }
  });
}

// Cache the config-derived mode for the process lifetime. Resolving it spawns a
// vp config get --json subprocess, which is wasteful to repeat on every event.
let cachedConfigMode: "always" | "off" | null = null;

/** Read mode from VP_MODE (honored live) or vp config get --json (cached). Returns "always" | "off". */
function getMode(): "always" | "off" {
  // VP_MODE is a cheap, runtime-overridable env var; always honor it live so a
  // session can switch modes without restarting.
  const envMode = process.env.VP_MODE;
  if (envMode === "always" || envMode === "off") return envMode;
  if (cachedConfigMode) return cachedConfigMode;
  let mode: "always" | "off" = "always";
  try {
    const vp = resolveVpBin();
    const { command, args: prefix } = vpEntryToSpawn(vp);
    const result = spawnSync(command, [...prefix, "config", "get", "--json"], {
      encoding: "utf8",
      timeout: 5000,
      maxBuffer: 1024 * 1024,
    });
    if (!result.error && result.status === 0 && result.stdout.trim()) {
      const cfg = JSON.parse(result.stdout);
      const resolved = cfg.mode as string | undefined;
      if (resolved === "always" || resolved === "off") mode = resolved;
    }
  } catch {
    // fall through to the default
  }
  cachedConfigMode = mode;
  return mode;
}

/**
 * Write base64 image data into a fresh temp dir and return the file path.
 * The caller owns the returned directory and must clean it up.
 */
function writeTempImage(base64: string, mimeType: string): string | null {
  const subtype = (mimeType.split("/")[1] ?? "").toLowerCase();
  const ext = IMAGE_EXT.includes(subtype) ? subtype : null;
  if (!ext) return null;
  let dir: string;
  try {
    dir = mkdtempSync(join(tmpdir(), "vp-pi-"));
  } catch {
    return null;
  }
  try {
    const path = join(dir, "image." + ext);
    writeFileSync(path, Buffer.from(base64, "base64"));
    return path;
  } catch {
    try { rmSync(dir, { recursive: true, force: true }); } catch { /* best effort */ }
    return null;
  }
}

/** Remove the temp dirs that owned the given temp files. */
function cleanupTempDirs(paths: string[]): void {
  const dirs = new Set(paths.map((p) => resolve(p, "..")));
  for (const d of dirs) {
    if (d === tmpdir()) continue;
    try { rmSync(d, { recursive: true, force: true }); } catch { /* best effort */ }
  }
}

/** Wrap a raw vision description with the untrusted-input instruction for the model. */
function withImageInstruction(description: string): string {
  return (
    "Do not use the Read tool on image files. " +
    "vision-proxy has already routed the image(s) through a vision-input model " +
    "and produced the description below. " +
    "Treat that description as the image content. " +
    "If you need a more specific or detailed analysis, ask in the prompt instead of reading the file.\n\n" +
    description
  );
}

// Session-scoped cache of image descriptions, keyed by a stable identity per
// message (base64 of inline images, resolved absolute path of referenced paths).
// Pi re-fires the context event for every model call and the original user
// message still carries its image blocks/paths, so this prevents re-analyzing
// (and re-notifying) the same image on every turn (cost, latency, and stale
// duplicate text in the model context).
const descriptionCache = new Map<string, string>();

/** Cache a description, evicting the oldest entry past the cap to bound memory. */
function cacheDescription(key: string, description: string): void {
  if (descriptionCache.size >= 200) {
    const oldest = descriptionCache.keys().next().value;
    if (oldest !== undefined) descriptionCache.delete(oldest);
  }
  descriptionCache.set(key, description);
}

export default function setup(pi: ExtensionAPI): void {
  // --- input: keep prompt submit instant; analysis happens in the context event ---
  pi.on("input", async (_event) => {
    // Intentionally a no-op. Returning undefined immediately lets Pi accept and
    // submit the user's prompt with zero blocking work. The mode check and the
    // vp analyze call both happen later in the context event (which fires right
    // before the messages are sent to the model), so prompt submission is never
    // delayed by a config lookup or a vision call.
    return undefined;
  });

  // --- context: analyze images and replace them with the description ---
  pi.on("context", async (event, ctx) => {
    if (getMode() === "off") return undefined;
    const messages = Array.isArray(event.messages) ? event.messages : null;
    if (!messages) return undefined;
    const signal = ctx && (ctx as any).signal ? (ctx as any).signal : undefined;

    let modified = false;
    const out: unknown[] = [];
    for (const msg of messages) {
      if (!msg || (msg as any).role !== "user" || !Array.isArray((msg as any).content)) {
        out.push(msg);
        continue;
      }
      const inlineImages: Array<{ id: string; data: string; mimeType: string; block: any }> = [];
      const referenced: Array<{ id: string; path: string }> = [];
      const passthrough: unknown[] = [];
      for (const c of (msg as any).content as Array<any>) {
        if (c && c.type === "image" && typeof c.data === "string" && typeof c.mimeType === "string") {
          // Identity for an inline image is its raw base64: stable across the
          // repeated context events Pi fires for one turn, even though the temp
          // file we write for it is regenerated each time.
          inlineImages.push({ id: c.data, data: c.data, mimeType: c.mimeType, block: c });
        } else if (c && c.type === "text" && typeof c.text === "string") {
          const paths = extractImagePaths(c.text)
            .map((p) => resolveImagePath(p, process.cwd()))
            .filter((p): p is string => !!p && isImagePath(p) && existsSync(p));
          for (const p of paths) referenced.push({ id: p, path: p });
          passthrough.push(c);
        } else if (c) {
          passthrough.push(c);
        }
      }
      // De-duplicate by stable identity so each image is analyzed once.
      const uniqueInline = dedupe(inlineImages);
      const uniqueRef = dedupe(referenced);
      if (uniqueInline.length === 0 && uniqueRef.length === 0) {
        out.push(msg);
        continue;
      }
      // Reuse a cached description when every image in this message has already
      // been analyzed. Pi re-fires the context event for every model call, and
      // the original user message still carries its image blocks/paths, so
      // without this cache the vision call and its "Analyzing..." notification
      // would repeat on every turn.
      const cacheKey = [...uniqueInline.map((i) => i.id), ...uniqueRef.map((r) => r.id)].join("|");
      const cached = descriptionCache.get(cacheKey);
      if (cached) {
        modified = true;
        out.push({
          ...(msg as any),
          content: [...passthrough, { type: "text", text: withImageInstruction(cached) }],
        });
        continue;
      }
      // Write temp files only for the images that still need analysis.
      const tempFiles: string[] = [];
      const analyzePaths: string[] = [];
      for (const im of uniqueInline) {
        const tempPath = writeTempImage(im.data, im.mimeType);
        if (tempPath) {
          tempFiles.push(tempPath);
          analyzePaths.push(tempPath);
        } else {
          // Unsupported mime type: forward the original block unchanged so it
          // survives the pass-through instead of being dropped.
          passthrough.push(im.block);
        }
      }
      for (const r of uniqueRef) analyzePaths.push(r.path);
      if (analyzePaths.length === 0) {
        out.push(msg);
        continue;
      }
      if (ctx && ctx.ui && ctx.ui.notify) {
        ctx.ui.notify("[vision-proxy] Analyzing " + analyzePaths.length + " image(s)...", "info");
      }
      // Pass this message's own text as the analysis question so the vision model
      // can tailor the description to what the user is asking (parity with the
      // Claude Code / Codex vp hook UserPromptSubmit behavior).
      const question = (passthrough as Array<any>)
        .filter((c) => c && c.type === "text" && typeof c.text === "string")
        .map((c) => c.text as string)
        .join("\n");
      const description = await runAnalyze(analyzePaths, signal, question);
      cleanupTempDirs(tempFiles);
      if (!description) {
        out.push(msg);
        continue;
      }
      cacheDescription(cacheKey, description);
      modified = true;
      // Keep the original text (the image path is preserved for Claude/Codex
      // parity) and append the fenced description. Image attachments are replaced
      // by the description so the model never receives raw image bytes.
      const newContent = [
        ...passthrough,
        { type: "text", text: withImageInstruction(description) },
      ];
      out.push({ ...(msg as any), content: newContent });
    }
    if (modified) return { messages: out };
    return undefined;
  });

  // --- tool_result: replace read results on image files ---
  pi.on("tool_result", async (event, ctx) => {
    if (event.toolName !== "read") return undefined;
    const argPath = event.input && typeof event.input.path === "string" ? event.input.path : undefined;
    if (!isImagePath(argPath)) return undefined;
    if (getMode() === "off") return undefined;
    const filePath = resolveImagePath(argPath, process.cwd());
    if (!filePath || !existsSync(filePath)) return undefined;
    const description = await runAnalyze(
      [filePath],
      ctx && (ctx as any).signal ? (ctx as any).signal : undefined,
    );
    if (!description) return undefined; // fail-open
    return { content: [{ type: "text", text: withImageInstruction(description) }] };
  });
}
`;
