# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing the permissions and
# limitations under the License.

name: OSV Scanner PR Check

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  osv-pr-scan:
    name: OSV Scanner PR Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run OSV-Scanner on base branch
        id: base
        uses: google/osv-scanner-action/osv-scanner-action@06b2ab4348248b456ee06c9e953637f55e03504f # v2.5.0
        env:
          GOTOOLCHAIN: auto
        continue-on-error: true
        with:
          scan-args: |-
            -r ./
            --lockfile=pnpm-lock.yaml
            --format=json
            --output=old-results.json

      - name: Run OSV-Scanner on PR branch
        uses: google/osv-scanner-action/osv-scanner-action@06b2ab4348248b456ee06c9e953637f55e03504f # v2.5.0
        env:
          GOTOOLCHAIN: auto
        with:
          scan-args: |-
            -r ./
            --lockfile=pnpm-lock.yaml
            --format=json
            --output=new-results.json
        continue-on-error: true

      - name: Compare and annotate PR
        uses: google/osv-scanner-action/osv-reporter-action@06b2ab4348248b456ee06c9e953637f55e03504f # v2.5.0
        with:
          scan-args: |-
            --output=results.sarif
            --old=old-results.json
            --new=new-results.json
            --gh-annotations=true
            --fail-on-vuln=true

      - name: Upload SARIF artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: OSV Scanner SARIF file
          path: results.sarif
          retention-days: 5

      - name: Upload to code scanning
        if: ${{ !cancelled() }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
